Weapons = {
    [`weapon_unarmed`] 				 = {label = 'Fists', image = 'WEAPON_UNARMED'},
    [`weapon_dagger`] 				 = {label = 'Dagger', image = 'WEAPON_DAGGER'},
    [`weapon_bat`] 					 = {label = 'Bat', image = 'WEAPON_BAT'},
    [`weapon_bottle`] 				 = {label = 'Broken Bottle', image = 'WEAPON_BOTTLE'},
    [`weapon_crowbar`] 				 = {label = 'Crowbar', image = 'WEAPON_CROWBAR'},
    [`weapon_flashlight`] 			 = {label = 'Flashlight', image = 'WEAPON_FLASHLIGHT'},
    [`weapon_golfclub`] 			 = {label = 'Golfclub', image = 'WEAPON_GOLFCLUB'},
    [`weapon_hammer`] 				 = {label = 'Hammer', image = 'WEAPON_HAMMER'},
    [`weapon_hatchet`] 				 = {label = 'Hatchet', image = 'WEAPON_HATCHET'},
    [`weapon_knuckle`] 				 = {label = 'Knuckle', image = 'WEAPON_KNUCKLE'},
    [`weapon_knife`] 				 = {label = 'Knife', image = 'WEAPON_KNIFE'},
    [`weapon_machete`] 				 = {label = 'Machete', image = 'WEAPON_MACHETE'},
    [`weapon_switchblade`] 			 = {label = 'Switchblade', image = 'WEAPON_SWITCHBLADE'},
    [`weapon_nightstick`] 			 = {label = 'Nightstick', image = 'WEAPON_NIGHTSTICK'},
    [`weapon_wrench`] 				 = {label = 'Wrench', image = 'WEAPON_WRENCH'},
    [`weapon_battleaxe`] 			 = {label = 'Battle Axe', image = 'WEAPON_BATTLEAXE'},
    [`weapon_poolcue`] 				 = {label = 'Poolcue', image = 'WEAPON_POOLCUE'},
    [`weapon_briefcase`] 			 = {label = 'Briefcase', image = 'WEAPON_BRIEFCASE'},
    [`weapon_briefcase_02`] 		 = {label = 'Briefcase', image = 'WEAPON_BRIEFCASE_02'},
    [`weapon_garbagebag`] 			 = {label = 'Garbage Bag', image = 'WEAPON_GARBAGEBAG'},
    [`weapon_handcuffs`] 			 = {label = 'Handcuffs', image = 'WEAPON_HANDCUFFS'},
    [`weapon_bread`] 				 = {label = 'Baquette', image = 'WEAPON_BREAD'},
    [`weapon_stone_hatchet`] 		 = {label = 'Stone Hatchet', image = 'WEAPON_STONE_HATCHET'},
    [`weapon_candycane`]             = {label = 'Candy Cane', image = 'WEAPON_CANDYCANE'},

    -- Handguns
    [`weapon_pistol`] 				 = {label = 'Pistol', image = 'WEAPON_PISTOL'},
    [`weapon_pistol_mk2`] 			 = {label = 'Pistol Mk2', image = 'WEAPON_PISTOL_MK2'},
    [`weapon_combatpistol`] 		 = {label = 'Combat Pistol', image = 'WEAPON_COMBATPISTOL'},
    [`weapon_appistol`] 			 = {label = 'AP Pistol', image = 'WEAPON_APPISTOL'},
    [`weapon_stungun`] 				 = {label = 'Taser', image = 'WEAPON_STUNGUN'},
    [`weapon_pistol50`] 			 = {label = 'Pistol .50 Cal', image = 'WEAPON_PISTOL50'},
    [`weapon_snspistol`] 			 = {label = 'SNS Pistol', image = 'WEAPON_SNSPISTOL'},
    [`weapon_snspistol_mk2`] 	     = {label = 'SNS Pistol MK2', image = 'WEAPON_SNSPISTOL_MK2'},
    [`weapon_heavypistol`] 			 = {label = 'Heavy Pistol', image = 'WEAPON_HEAVYPISTOL'},
    [`weapon_vintagepistol`] 		 = {label = 'Vintage Pistol', image = 'WEAPON_VINTAGEPISTOL'},
    [`weapon_flaregun`] 			 = {label = 'Flare Gun', image = 'WEAPON_FLAREGUN'},
    [`weapon_marksmanpistol`] 		 = {label = 'Marksman Pistol', image = 'WEAPON_MARKSMANPISTOL'},
    [`weapon_revolver`] 			 = {label = 'Revolver', image = 'WEAPON_REVOLVER'},
    [`weapon_revolver_mk2`] 		 = {label = 'Revolver MK2', image = 'WEAPON_REVOLVER_MK2'},
    [`weapon_doubleaction`] 	     = {label = 'Double Action Revolver', image = 'WEAPON_DOUBLEACTION'},
    [`weapon_raypistol`]			 = {label = 'Ray Pistol', image = 'WEAPON_RAYPISTOL'},
    [`weapon_ceramicpistol`]		 = {label = 'Ceramic Pistol', image = 'WEAPON_CERAMICPISTOL'},
    [`weapon_navyrevolver`]        	 = {label = 'Navy Revolver', image = 'WEAPON_NAVYREVOLVER'},
    [`weapon_gadgetpistol`] 		 = {label = 'Gadget Pistol', image = 'WEAPON_GADGETPISTOL'},
    [`weapon_stungun_mp`] 			 = {label = 'Taser', image = 'WEAPON_STUNGUN_MP'},

    -- Submachine Guns
    [`weapon_microsmg`] 			 = {label = 'Micro SMG', image = 'WEAPON_MICROSMG'},
    [`weapon_smg`] 				 	 = {label = 'SMG', image = 'WEAPON_SMG'},
    [`weapon_smg_mk2`] 				 = {label = 'SMG MK2', image = 'WEAPON_SMG_MK2'},
    [`weapon_assaultsmg`] 			 = {label = 'Assault SMG', image = 'WEAPON_ASSAULTSMG'},
    [`weapon_combatpdw`] 			 = {label = 'Combat PDW', image = 'WEAPON_COMBATPDW'},
    [`weapon_machinepistol`] 		 = {label = 'Tec-9', image = 'WEAPON_MACHINEPISTOL'},
    [`weapon_minismg`] 				 = {label = 'Mini SMG', image = 'WEAPON_MINISMG'},
    [`weapon_raycarbine`]	         = {label = 'Raycarbine', image = 'WEAPON_RAYCARBINE'},

    -- Shotguns
    [`weapon_pumpshotgun`] 			 = {label = 'Pump Shotgun', image = 'WEAPON_PUMPSHOTGUN'},
    [`weapon_pumpshotgun_mk2`]		 = {label = 'Pump Shotgun MK2', image = 'WEAPON_PUMPSHOTGUN_MK2'},
    [`weapon_sawnoffshotgun`] 		 = {label = 'Sawn-off Shotgun', image = 'WEAPON_SAWNOFFSHOTGUN'},
    [`weapon_assaultshotgun`] 		 = {label = 'Assault Shotgun', image = 'WEAPON_ASSAULTSHOTGUN'},
    [`weapon_bullpupshotgun`] 		 = {label = 'Bullpup Shotgun', image = 'WEAPON_BULLPUPSHOTGUN'},
    [`weapon_musket`] 			     = {label = 'Musket', image = 'WEAPON_MUSKET'},
    [`weapon_heavyshotgun`] 		 = {label = 'Heavy Shotgun', image = 'WEAPON_HEAVYSHOTGUN'},
    [`weapon_dbshotgun`] 			 = {label = 'Double-barrel Shotgun', image = 'WEAPON_DBSHOTGUN'},
    [`weapon_autoshotgun`] 			 = {label = 'Auto Shotgun', image = 'WEAPON_AUTOSHOTGUN'},
    [`weapon_combatshotgun`]		 = {label = 'Combat Shotgun', image = 'WEAPON_COMBATSHOTGUN'},

    -- Assault Rifles
    [`weapon_assaultrifle`] 		 = {label = 'Assault Rifle', image = 'WEAPON_ASSAULTRIFLE'},
    [`weapon_assaultrifle_mk2`] 	 = {label = 'Assault Rifle MK2', image = 'WEAPON_ASSAULTRIFLE_MK2'},
    [`weapon_carbinerifle`] 		 = {label = 'Carbine Rifle', image = 'WEAPON_CARBINERIFLE'},
    [`weapon_carbinerifle_mk2`] 	 = {label = 'Carbine Rifle MK2', image = 'WEAPON_CARBINERIFLE_MK2'},
    [`weapon_advancedrifle`] 		 = {label = 'Advanced Rifle', image = 'WEAPON_ADVANCEDRIFLE'},
    [`weapon_specialcarbine`] 		 = {label = 'Special Carbine', image = 'WEAPON_SPECIALCARBINE'},
    [`weapon_specialcarbine_mk2`]	 = {label = 'Specialcarbine MK2', image = 'WEAPON_SPECIALCARBINE_MK2'},
    [`weapon_bullpuprifle`] 		 = {label = 'Bullpup Rifle', image = 'WEAPON_BULLPUPRIFLE'},
    [`weapon_bullpuprifle_mk2`]		 = {label = 'Bull Puprifle MK2', image = 'WEAPON_BULLPUPRIFLE_MK2'},
    [`weapon_compactrifle`] 		 = {label = 'Compact Rifle', image = 'WEAPON_COMPACTRIFLE'},
    [`weapon_militaryrifle`]		 = {label = 'Military Rifle', image = 'WEAPON_MILITARYRIFLE'},
    [`weapon_heavyrifle`] 			 = {label = 'Heavy Rifle', image = 'WEAPON_HEAVYRIFLE'},
    [`weapon_tacticalrifle`] 		 = {label = 'Service Rifle', image = 'WEAPON_TACTICALRIFLE'},

    -- Light Machine Guns
    [`weapon_mg`] 					 = {label = 'Machinegun', image = 'WEAPON_MG'},
    [`weapon_combatmg`] 			 = {label = 'Combat MG', image = 'WEAPON_COMBATMG'},
    [`weapon_combatmg_mk2`]	 		 = {label = 'Combat MG MK2', image = 'WEAPON_COMBATMG_MK2'},
    [`weapon_gusenberg`] 			 = {label = 'Thompson SMG', image = 'WEAPON_GUSENBERG'},

    -- Sniper Rifles
    [`weapon_sniperrifle`] 			 = {label = 'Sniper Rifle', image = 'WEAPON_SNIPERRIFLE'},
    [`weapon_heavysniper`] 			 = {label = 'Heavy Sniper', image = 'WEAPON_HEAVYSNIPER'},
    [`weapon_heavysniper_mk2`]		 = {label = 'Heavysniper MK2', image = 'WEAPON_HEAVYSNIPER_MK2'},
    [`weapon_marksmanrifle`] 		 = {label = 'Marksman Rifle', image = 'WEAPON_MARKSMANRIFLE'},
    [`weapon_marksmanrifle_mk2`]	 = {label = 'Marksman Rifle MK2', image = 'WEAPON_MARKSMANRIFLE_MK2'},
    [`weapon_remotesniper`] 		 = {label = 'Remote Sniper', image = 'WEAPON_REMOTESNIPER'},
    [`weapon_precisionrifle`] 		 = {label = 'Precision Rifle', image = 'WEAPON_PRECISIONRIFLE'},

    -- Heavy Weapons
    [`weapon_rpg`] 					 = {label = 'RPG', image = 'WEAPON_RPG'},
    [`weapon_grenadelauncher`] 		 = {label = 'Grenade Launcher', image = 'WEAPON_GRENADELAUNCHER'},
    [`weapon_grenadelauncher_smoke`] = {label = 'Smoke Grenade Launcher', image = 'WEAPON_GRENADELAUNCHER_SMOKE'},
    [`weapon_minigun`] 				 = {label = 'Minigun', image = 'WEAPON_MINIGUN'},
    [`weapon_firework`] 			 = {label = 'Firework Launcher', image = 'WEAPON_FIREWORK'},
    [`weapon_railgun`] 				 = {label = 'Railgun', image = 'WEAPON_RAILGUN'},
    [`weapon_hominglauncher`] 		 = {label = 'Homing Launcher', image = 'WEAPON_HOMINGLAUNCHER'},
    [`weapon_compactlauncher`] 		 = {label = 'Compact Launcher', image = 'WEAPON_COMPACTLAUNCHER'},
    [`weapon_rayminigun`]			 = {label = 'Ray Minigun', image = 'WEAPON_RAYMINIGUN'},
    [`weapon_emplauncher`] 			 = {label = 'EMP Launcher', image = 'WEAPON_EMPLAUNCHER'},

    -- Throwables
    [`weapon_grenade`] 		        = {label = 'Grenade', image = 'WEAPON_GRENADE'},
    [`weapon_bzgas`] 		        = {label = 'BZ Gas', image = 'WEAPON_BZGAS'},
    [`weapon_molotov`] 		        = {label = 'Molotov', image = 'WEAPON_MOLOTOV'},
    [`weapon_stickybomb`] 	        = {label = 'C4', image = 'WEAPON_STICKYBOMB'},
    [`weapon_proxmine`] 	        = {label = 'Proxmine Grenade', image = 'WEAPON_PROXMINE'},
    [`weapon_snowball`] 	        = {label = 'Snowball', image = 'WEAPON_SNOWBALL'},
    [`weapon_pipebomb`] 	        = {label = 'Pipe Bomb', image = 'WEAPON_PIPEBOMB'},
    [`weapon_ball`] 		        = {label = 'Ball', image = 'WEAPON_BALL'},
    [`weapon_smokegrenade`]         = {label = 'Smoke Grenade', image = 'WEAPON_SMOKEGRENADE'},
    [`weapon_flare`] 		        = {label = 'Flare pistol', image = 'WEAPON_FLARE'},

    -- Miscellaneous
    [`weapon_petrolcan`] 			= {label = 'Petrol Can', image = 'WEAPON_PETROLCAN'},
    [`gadget_parachute`] 			= {label = 'Parachute', image = 'GADGET_PARACHUTE'},
    [`weapon_fireextinguisher`] 	= {label = 'Fire Extinguisher', image = 'WEAPON_FIREEXTINGUISHER'},
    [`weapon_hazardcan`]			= {label = 'Hazardcan', image = 'WEAPON_HAZARDCAN'},
    [`weapon_fertilizercan`]		= {label = 'Fertilizer Can', image = 'WEAPON_FERTILIZERCAN'},
    [`weapon_barbed_wire`]			= {label = 'Barbed Wire', image = 'WEAPON_BARBED_WIRE'},
    [`weapon_drowning`]				= {label = 'Drowning', image = 'WEAPON_DROWNING'},
    [`weapon_drowning_in_vehicle`]	= {label = 'Drowning in a Vehicle', image = 'WEAPON_DROWNING_IN_VEHICLE'},
    [`weapon_bleeding`]				= {label = 'Bleeding', image = 'WEAPON_BLEEDING'},
    [`weapon_electric_fence`]		= {label = 'Electric Fence', image = 'WEAPON_ELECTRIC_FENCE'},
    [`weapon_explosion`]			= {label = 'Explosion', image = 'WEAPON_EXPLOSION'},
    [`weapon_fall`]					= {label = 'Fall', image = 'WEAPON_FALL'},
    [`weapon_exhaustion`]			= {label = 'Exhaustion', image = 'WEAPON_EXHAUSTION'},
    [`weapon_hit_by_water_cannon`]	= {label = 'Water Cannon', image = 'WEAPON_HIT_BY_WATER_CANNON'},
    [`weapon_rammed_by_car`]		= {label = 'Rammed - Vehicle', image = 'WEAPON_RAMMED_BY_CAR'},
    [`weapon_run_over_by_car`]		= {label = 'Run Over - Vehicle', image = 'WEAPON_RUN_OVER_BY_CAR'},
    [`weapon_heli_crash`]			= {label = 'Heli Crash', image = 'WEAPON_HELI_CRASH'},
    [`weapon_fire`]					= {label = 'Fire', image = 'WEAPON_FIRE'},
    [`weapon_metaldetector`] 		= {label = 'Metal Dectector', image = 'WEAPON_METALDETECTOR'},

    -- Animals
    [`weapon_animal`]               = {label = 'Animal', image = 'WEAPON_ANIMAL'},
    [`weapon_cougar`]               = {label = 'Cougar', image = 'WEAPON_COUGAR'},
}