Config = Config or {}

Config.ClassId = 'vampiro'
Config.ClassMetadataKey = 'classe'

Config.Hud = {
    position = {
        right = '2.2vw',
        bottom = '1.8vh',
        scale = 1.18,
    },
    theme = {
        accent = '#b9293f',
        accentSoft = '#290a10',
        frameHue = '-34deg',
    },
}

Config.Essence = {
    resource = 'ob_essencias',
    removeExport = 'RemoveEssencia',
}

Config.SolarWeakness = {
    enabled = true,
    shadowStep = {
        sprintMultiplier = 1.18,
        moveRate = 1.12,
        highJump = false,
    },
    batForm = {
        sustainCostMultiplier = 4.0,
    },
    hypnosis = {
        successChance = 55,
        durationMultiplier = 0.45,
    },
    nightEmbrace = {
        damageMultiplier = 0.45,
        healthGainMultiplier = 0.35,
        essenceGainMultiplier = 1.0,
    },
}

Config.ShadowStep = {
    cooldown = 52000,
    essenceCost = 2,
    sustainCost = 4,
    sustainInterval = 5000,
    sustainGrace = 3000,
    sprintMultiplier = 1.45,
    moveRate = 1.35,
    highJump = true,
    effect = {
        smokeAsset = 'scr_powerplay',
        smokeName = 'sp_powerplay_beast_appear_trails',
        smokeColor = { 0.72, 0.01, 0.02 },
        smokeAlpha = 0.42,
        smokeScale = 6.0,
        smokeBurstCooldown = 500,
        smokeMinimumSpeed = 1.2,
        smokeSyncRange = 50.0,
        smokeSyncInterval = 500,
        distortionAsset = 'scr_xm_heat',
        distortionName = 'scr_xm_heat_camo',
        distortionScale = 1.3,
        distortionMinimumKmh = 40.0,
    },
}

Config.BatForm = {
    model = 'sera_bat_01',
    components = {
        { id = 0, drawable = 0, texture = 4 },
        { id = 8, drawable = 0, texture = 4 },
    },
    returnCooldown = 50000,
    transitionTime = 1450,
    smokeDuration = 1700,
    essenceCost = 0,
    sustainCost = 2,
    sustainInterval = 8000,
    sustainGrace = 3000,
    preserveHealth = true,
    protectedHealth = 2000,
    transformationFx = {
        smokeAsset = 'core',
        smokeName = 'exp_grd_grenade_smoke',
        smokeColor = { 0.24, 0.0, 0.02 },
        smokeAlpha = 0.9,
        smokeScale = 1.25,
        trailAsset = 'scr_powerplay',
        trailName = 'sp_powerplay_beast_appear_trails',
        trailColor = { 0.72, 0.01, 0.025 },
        trailAlpha = 0.58,
        trailScale = 4.6,
        pulses = 3,
        pulseInterval = 125,
        syncRange = 65.0,
    },
    flightDistortion = {
        asset = 'scr_xm_heat',
        name = 'scr_xm_heat_camo',
        scale = 1.05,
        minimumSpeed = 2.5,
    },
}

Config.Hypnosis = {
    distance = 40.0,
    beamWidth = 5.0,
    cooldown = 30000,
    essenceCost = 14,
    duration = 10000,
    castTime = 850,
    beamStep = 0.85,
    beamFxScale = 1.55,
    beamFxLife = 320,
    beamColor = { 1.0, 0.0, 0.015 },
    beamAlpha = 0.8,
    headFx = {
        radius = 0.32,
        height = 0.12,
        speed = 0.006,
        scale = 0.42,
        alpha = 0.9,
        pulseInterval = 65,
        pulseLife = 380,
    },
    blurStrength = 0.62,
    npcControlTimeout = 1000,
}

Config.NightEmbrace = {
    distance = 15.0,
    allowFarmPumaTarget = true,
    cooldown = 35000,
    essenceCost = 0,
    channelDuration = 7000,
    drainAmount = 25,
    healthGain = 25,
    essenceGain = 4,
    pumaEssenceGain = 4,
    ticks = 10,
    minimumTargetHealth = 105,
    npcControlTimeout = 1200,
    pumaGrip = {
        bone = 0,
        offset = { x = 0.18, y = 0.45, z = 0.95 },
        rotation = { x = 0.0, y = 0.0, z = 90.0 },
        ragdollDelay = 180,
        releaseRagdoll = 1400,
        dropForward = 1.25,
        dropSide = 0.65,
        dropClearance = 0.08,
    },
    biteAnimation = {
        dictionary = 'r9@feed@new',
        casterClip = 'master',
        targetClip = 'slave',
        loadTimeout = 8000,
        alignmentDelay = 250,
        targetOffset = { x = 0.10, y = 0.45, z = 0.0 },
        blendIn = 1.0,
        blendOut = 1.0,
        casterFlag = 32,
        targetFlag = 1,
        aftermathRagdoll = 6000,
        approach = {
            speed = 18.0,
            minimumDuration = 320,
            maximumDuration = 900,
            height = 0.32,
            dictionary = 'export@nib@super@basicflight_fast_botharmsback',
            clip = 'nib@super@basicflight_fast_botharmsback',
            flag = 1,
            loadTimeout = 3000,
            effect = {
                asset = 'scr_powerplay',
                name = 'sp_powerplay_beast_appear_trails',
                color = { 0.52, 0.0, 0.055 },
                alpha = 0.92,
                scale = 4.8,
                pulseInterval = 105,
                hideBody = true,
                syncRange = 65.0,
            },
        },
    },
    transformationEnabled = false,
    transformationAce = 'ob_vampiros.transform',
}

Config.PumaFarm = {
    enabled = true,
    models = { 'a_c_mtlion' },
    targetName = 'ob_vampiros_sugar_puma',
    targetLabel = 'Sugar sangue do puma',
    targetIcon = 'fa-solid fa-droplet',
    interactionDistance = 2.2,
    serverDistance = 4.0,
    actionDuration = 8000,
    cancelDistance = 3.6,
    lockTimeout = 16000,
    cleanupDelay = 45000,
    collection = {
        targetName = 'ob_vampiros_coletar_puma',
        targetLabel = 'Recolher sangue da puma',
        targetIcon = 'fa-solid fa-vial',
        progressLabel = 'Enchendo o frasco com sangue da puma',
        requiredItem = 'frasco_vazio',
        requiredItemLabel = 'Frasco vazio',
        requiredAmount = 1,
        consumeRequiredItem = true,
    },
    feeding = {
        targetName = 'ob_vampiros_sugar_puma',
        targetLabel = 'Sugar sangue da puma',
        targetIcon = 'fa-solid fa-droplet',
        progressLabel = 'Absorvendo a essencia do sangue',
        essenceGain = 30,
    },
    spawn = {
        enabled = true,
        maxActive = 4,
        checkInterval = 5000,
        maxSpawnPerCycle = 1,
        respawnDelay = 90000,
        unharvestedCorpseLifetime = 600000,
        activationDistance = 220.0,
        despawnDistance = 320.0,
        minimumPlayerDistance = 28.0,
        routingBucket = 0,
        roamRadius = 45.0,
        aggressive = true,
        detectionDistance = 35.0,
        initialSpawnHeight = 1.5,
        groundProbeHeight = 75.0,
        groundClearance = 0.04,
        groundSettleTimeout = 3000,
        points = {
            vec4(3706.6, 4918.1, 16.19, 194.31),
            vec4(3705.8, 4905.82, 17.05, 183.51),
            vec4(3719.66, 4907.63, 17.58, 51.72),
            vec4(3711.02, 4924.53, 15.67, 17.56),
            vec4(3713.52, 4940.04, 20.83, 110.9),
            vec4(3698.92, 4952.88, 18.76, 46.61),
            vec4(3680.12, 4937.65, 16.32, 145.81),
            vec4(3667.15, 4923.01, 12.82, 111.63),
            vec4(3650.52, 4928.03, 11.68, 56.12),
            vec4(3637.91, 4939.02, 10.35, 42.31),
            vec4(3637.59, 4955.54, 10.91, 340.13),
            vec4(3658.48, 4978.16, 11.35, 337.52),
            vec4(3644.12, 4989.03, 10.12, 72.8),
            vec4(3625.97, 4993.7, 10.22, 85.17),
            vec4(3614.46, 5004.67, 9.1, 31.86),
            vec4(3603.36, 5021.32, 7.86, 354.95),
            vec4(3627.33, 5034.39, 9.93, 235.96),
        },
    },
    rewards = {
        { item = 'sangue_puma', label = 'Sangue de puma', min = 1, max = 1, chance = 100 },
        { item = 'carne_puma', label = 'Carne de puma', min = 1, max = 2, chance = 70 },
        { item = 'couro_puma', label = 'Couro de puma', min = 1, max = 1, chance = 38 },
    },
    animation = {
        enter = {
            dictionary = 'amb@medic@standing@kneel@enter',
            clip = 'enter',
            duration = 1050,
            flag = 2,
        },
        feed = {
            dictionary = 'amb@medic@standing@tendtodead@idle_a',
            clip = 'idle_a',
            flag = 1,
        },
        exit = {
            dictionary = 'amb@medic@standing@kneel@exit',
            clip = 'exit',
            duration = 850,
            flag = 2,
        },
    },
    effect = {
        enabled = true,
        asset = 'core',
        name = 'blood_stab',
        scale = 0.55,
        interval = 1350,
    },
}
