Config.Music = {}

Config.Music.maxRecent = 24
Config.Music.generatedCategoryTracks = 20
Config.Music.defaultAccent = 'bg-blue-500'

Config.Music.playlists = {
    {
        id = 'qs1',
        name = 'Quasar #WORLD: Volume 1',
        accentClass = 'bg-rose-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=cAdKznTKVsQ', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Coding Craft' },
            { url = 'https://www.youtube.com/watch?v=fmHw7fa_cEU', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'King of the Motel' },
            { url = 'https://www.youtube.com/watch?v=Z_EGYslDbJY', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Race Kings' },
            { url = 'https://www.youtube.com/watch?v=Jw3Ln2aG0go', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Deathmatch Legends' },
            { url = 'https://www.youtube.com/watch?v=MVRvr7GYuwM', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Digital Skyline' },
            { url = 'https://www.youtube.com/watch?v=cH699l7kBcA', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Rare to Legendary' },
            { url = 'https://www.youtube.com/watch?v=EVzUhMQfdJM', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Forge Your Legacy Beneath the Surface' },
            { url = 'https://www.youtube.com/watch?v=1ZbW9q6KMws', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Rollin’ in Motorhome' },
            { url = 'https://www.youtube.com/watch?v=tItUqm7dsck', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Beyond the Scoreboard' },
            { url = 'https://www.youtube.com/watch?v=SPmZFbZW5pI', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Al Laburo' },
            { url = 'https://www.youtube.com/watch?v=Bb0dBu-RsxM', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e026037c13fd8ff9891e1a3bc7d', title = 'Toxic Attraction' },
        },
    },
    {
        id = 'qs2',
        name = 'Quasar #WORLD: Volume 2',
        accentClass = 'bg-violet-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=d15nKSGYpCE', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'Be careful, its floating' },
            { url = 'https://www.youtube.com/watch?v=aLUO95JZIAA', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'Cyber Drift' },
            { url = 'https://www.youtube.com/watch?v=Uk4Lxg7YxII', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'De Ruta' },
            { url = 'https://www.youtube.com/watch?v=s1L_kYH7eJ0', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'Doggy Empire' },
            { url = 'https://www.youtube.com/watch?v=IZj1WnrJnu8', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'Double Tap' },
            { url = 'https://www.youtube.com/watch?v=OGuo6f3bg4k', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'Every Outfit' },
            { url = 'https://www.youtube.com/watch?v=QNxXAk_2lRg', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'High Life' },
            { url = 'https://www.youtube.com/watch?v=AMEnZpmBfPI', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'High Stakes' },
            { url = 'https://www.youtube.com/watch?v=mwiR5DieYZ8', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'No Delay, Just Play' },
            { url = 'https://www.youtube.com/watch?v=YnjWe-Qdlro', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e022ad758125b193893101151a5', title = 'Prr Prr Gang' },
        },
    },
    {
        id = 'qs3',
        name = 'Quasar #WORLD: Volume 3',
        accentClass = 'bg-amber-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=mt9uE15xqMI', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Al Laburo (remastered)' },
            { url = 'https://www.youtube.com/watch?v=9lfmvu4YloY', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Chameleon' },
            { url = 'https://www.youtube.com/watch?v=nzlculYdW6o', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Get a Job?' },
            { url = 'https://www.youtube.com/watch?v=i9x3OExSKH8', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Gordos Lloran en Squad' },
            { url = 'https://www.youtube.com/watch?v=1Tv-ZnzqE20', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Hoy soy  Cana, Mañana Chorro' },
            { url = 'https://www.youtube.com/watch?v=h_GTFMyJrqA', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Il Giornalaio' },
            { url = 'https://www.youtube.com/watch?v=Bq-B3DCJmso', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Job Creator on City' },
            { url = 'https://www.youtube.com/watch?v=eH5QDhCw_eY', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'RATATATA' },
            { url = 'https://www.youtube.com/watch?v=ViJV1O4j1_w', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Route King' },
            { url = 'https://www.youtube.com/watch?v=ahov9D8zNDw', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Sloth Talk (spanish)' },
            { url = 'https://www.youtube.com/watch?v=RTYkvHYEfrU', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e0206e71a76cee806e0e11ac2a7', title = 'Trucker Life, Quasar Style' },
        },
    },
    {
        id = 'qs4',
        name = 'Monte Everest',
        accentClass = 'bg-cyan-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=Do57JDlTJj4', artist = 'Quasar Store', cover = 'https://i.ytimg.com/vi/Do57JDlTJj4/maxresdefault.jpg', title = 'Monte Everest' },
        },
    },
    {
        id = 'qs5',
        name = 'Glitched Reality',
        accentClass = 'bg-lime-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=WJ_aLBfiG34', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e020c254b8119cbe6ca34785475', title = 'Un Paso de Aqui' },
            { url = 'https://www.youtube.com/watch?v=Ns7IZB0SzA8', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e020c254b8119cbe6ca34785475', title = 'Milonga en Ruinas' },
            { url = 'https://www.youtube.com/watch?v=TYc38JQXYjU', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e020c254b8119cbe6ca34785475', title = 'Gone Fishing... Again' },
            { url = 'https://www.youtube.com/watch?v=HmXdvA26g84', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e020c254b8119cbe6ca34785475', title = 'Yami no Oku de Hikaru Mono' },
            { url = 'https://www.youtube.com/watch?v=ofwBD6qSfXw', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e020c254b8119cbe6ca34785475', title = 'No Time to Blink' },
            { url = 'https://www.youtube.com/watch?v=jz0wfx-7bgs', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e020c254b8119cbe6ca34785475', title = 'Underground Control' },
            { url = 'https://www.youtube.com/watch?v=vjpDv4tz2Qc', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e020c254b8119cbe6ca34785475', title = 'Born to Drift' },
        },
    },
    {
        id = 'qs6',
        name = 'Biohazard',
        accentClass = 'bg-red-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=8WvA-W3OYAA', artist = 'Quasar Store', cover = 'https://i.ibb.co/8L1yYTd7/imagen-2026-04-17-230353718.png', title = 'Biohazard' },
        },
    },
    {
        id = 'qs7',
        name = 'El Escondite',
        accentClass = 'bg-red-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=sfa8xrOKuNE', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e02f4290d5ff5b99105acebc42a', title = 'El Escondite' },
        },
    },

    {
        id = 'qs8',
        name = 'Canceled',
        accentClass = 'bg-red-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=sNLRi3fhZlk', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e02dde0a1a9e41b4c2c031e9bae', title = 'Build It, Race It (nobody like us)' },
            { url = 'https://www.youtube.com/watch?v=Y1n8B8TqMVo', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e02dde0a1a9e41b4c2c031e9bae', title = 'Lock It Down' },
            { url = 'https://www.youtube.com/watch?v=LSXbofkYWQM', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e02dde0a1a9e41b4c2c031e9bae', title = 'Made in Quasar' },
            { url = 'https://www.youtube.com/watch?v=omQgAu0jy4g', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e02dde0a1a9e41b4c2c031e9bae', title = 'Race Kings' },
            { url = 'https://www.youtube.com/watch?v=Uki8lLBUpCk', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e02dde0a1a9e41b4c2c031e9bae', title = 'Wheels on Fire' },
            { url = 'https://www.youtube.com/watch?v=BAQp7NDVqx8', artist = 'Quasar Store', cover = 'https://i.scdn.co/image/ab67616d00001e02dde0a1a9e41b4c2c031e9bae', title = 'The House Everyone Copies' },
        },
    },
}

--[[ Config.Music.playlists = {
    {
        id = 'rock',
        name = 'Rock',
        accentClass = 'bg-rose-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=8SbUC-UaAxE', artist = 'GunsNRosesVEVO', cover = 'https://i.ytimg.com/vi/8SbUC-UaAxE/maxresdefault.jpg', title = "Guns N' Roses - November Rain" },
            { url = 'https://www.youtube.com/watch?v=djV11Xbc914', artist = 'a-ha',           cover = 'https://i.ytimg.com/vi/djV11Xbc914/maxresdefault.jpg', title = 'a-ha - Take On Me (Official Video) [4K]' },
            { url = 'https://www.youtube.com/watch?v=hTWKbfoikeg', artist = 'NirvanaVEVO',    cover = 'https://i.ytimg.com/vi/hTWKbfoikeg/maxresdefault.jpg', title = 'Nirvana - Smells Like Teen Spirit (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=1w7OgIMMRc4', artist = 'GunsNRosesVEVO', cover = 'https://i.ytimg.com/vi/1w7OgIMMRc4/maxresdefault.jpg', title = "Guns N' Roses - Sweet Child O' Mine (Official Music Video)" },
            { url = 'https://www.youtube.com/watch?v=9jK-NcRmVcw', artist = 'EuropeVEVO',     cover = 'https://i.ytimg.com/vi/9jK-NcRmVcw/maxresdefault.jpg', title = 'Europe - The Final Countdown (Official Video)' },
            { url = 'https://www.youtube.com/watch?v=OMOGaugKpzs', artist = 'ThePoliceVEVO',  cover = 'https://i.ytimg.com/vi/OMOGaugKpzs/maxresdefault.jpg', title = 'The Police - Every Breath You Take (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=xwtdhWltSIg', artist = 'remhq',          cover = 'https://i.ytimg.com/vi/xwtdhWltSIg/maxresdefault.jpg', title = 'R.E.M. - Losing My Religion (Official HD Music Video)' },
            { url = 'https://www.youtube.com/watch?v=btPJPFnesV4', artist = 'SurvivorVEVO',   cover = 'https://i.ytimg.com/vi/btPJPFnesV4/maxresdefault.jpg', title = 'Survivor - Eye Of The Tiger (Official HD Video)' },
            { url = 'https://www.youtube.com/watch?v=zRIbf6JqkNc', artist = 'GunsNRosesVEVO', cover = 'https://i.ytimg.com/vi/zRIbf6JqkNc/maxresdefault.jpg', title = "Guns N' Roses - Don't Cry" },
            { url = 'https://www.youtube.com/watch?v=Rbm6GXllBiw', artist = 'GunsNRosesVEVO', cover = 'https://i.ytimg.com/vi/Rbm6GXllBiw/maxresdefault.jpg', title = "Guns N' Roses - Paradise City (Official Music Video)" },
            { url = 'https://www.youtube.com/watch?v=ErvgV4P6Fzc', artist = 'GunsNRosesVEVO', cover = 'https://i.ytimg.com/vi/ErvgV4P6Fzc/maxresdefault.jpg', title = "Guns N' Roses - Patience" },
            { url = 'https://www.youtube.com/watch?v=NMNgbISmF4I', artist = 'AerosmithVEVO',  cover = 'https://i.ytimg.com/vi/NMNgbISmF4I/maxresdefault.jpg', title = 'Aerosmith - Crazy (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=qeMFqkcPYcg', artist = 'EurythmicsVEVO', cover = 'https://i.ytimg.com/vi/qeMFqkcPYcg/maxresdefault.jpg', title = 'Eurythmics, Annie Lennox, Dave Stewart - Sweet Dreams (Are Made Of This) (Official Video)' },
            { url = 'https://www.youtube.com/watch?v=UrIiLvg58SY', artist = 'ExtremeVEVO',    cover = 'https://i.ytimg.com/vi/UrIiLvg58SY/maxresdefault.jpg', title = 'Extreme - More Than Words (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=YR5ApYxkU-U', artist = 'mongchilde',     cover = 'https://i.ytimg.com/vi/YR5ApYxkU-U/maxresdefault.jpg', title = 'Pink Floyd - Another Brick In The Wall (HQ)' },
            { url = 'https://www.youtube.com/watch?v=rY0WxgSXdEE', artist = 'Queen Official', cover = 'https://i.ytimg.com/vi/rY0WxgSXdEE/maxresdefault.jpg', title = 'Queen - Another One Bites the Dust (Official Video)' },
            { url = 'https://www.youtube.com/watch?v=o1tj2zJ2Wvg', artist = 'GunsNRosesVEVO', cover = 'https://i.ytimg.com/vi/o1tj2zJ2Wvg/maxresdefault.jpg', title = "Guns N' Roses - Welcome To The Jungle" },
            { url = 'https://www.youtube.com/watch?v=JkK8g6FMEXE', artist = 'AerosmithVEVO',  cover = 'https://i.ytimg.com/vi/JkK8g6FMEXE/maxresdefault.jpg', title = "Aerosmith - I Don't Want to Miss a Thing (Official HD Video)" },
            { url = 'https://www.youtube.com/watch?v=vabnZ9-ex7o', artist = 'NirvanaVEVO',    cover = 'https://i.ytimg.com/vi/vabnZ9-ex7o/maxresdefault.jpg', title = 'Nirvana - Come As You Are (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=Qt2mbGP6vFI', artist = 'Phil Collins',   cover = 'https://i.ytimg.com/vi/Qt2mbGP6vFI/sddefault.jpg',     title = 'Phil Collins - Another Day In Paradise (Official Music Video)' },
        },
    },
    {
        id = 'trap',
        name = 'Trap',
        accentClass = 'bg-violet-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=IafCTjajefE', artist = 'MigosVEVO',           cover = 'https://i.ytimg.com/vi/IafCTjajefE/maxresdefault.jpg', title = 'Offset - Clout  ft. Cardi B (Audio)' },
            { url = 'https://www.youtube.com/watch?v=b3lH6CULHD0', artist = 'Loku',                cover = 'https://i.ytimg.com/vi/b3lH6CULHD0/maxresdefault.jpg', title = 'Drake - Money In The Grave (Lyrics) ft. Rick Ross' },
            { url = 'https://www.youtube.com/watch?v=yAk11Jtrz0A', artist = 'MustardVEVO',         cover = 'https://i.ytimg.com/vi/yAk11Jtrz0A/maxresdefault.jpg', title = 'Mustard, Migos - Pure Water (Audio)' },
            { url = 'https://www.youtube.com/watch?v=Jd6q69hO6X4', artist = 'Roddy Ricch',         cover = 'https://i.ytimg.com/vi/Jd6q69hO6X4/maxresdefault.jpg', title = 'Roddy Ricch - Peta (feat. Meek Mill) [Official Audio]' },
            { url = 'https://www.youtube.com/watch?v=51SD43kxyJc', artist = 'Wale',                cover = 'https://i.ytimg.com/vi/51SD43kxyJc/maxresdefault.jpg', title = 'Wale - Routine (feat. Rick Ross & Meek Mill) [Official Lyrics Video]' },
            { url = 'https://www.youtube.com/watch?v=vLDYEHqZdqk', artist = 'Offset - Topic',      cover = 'https://i.ytimg.com/vi/vLDYEHqZdqk/maxresdefault.jpg', title = 'Red Room' },
            { url = 'https://www.youtube.com/watch?v=rOVsNCo_2d4', artist = 'FutureHype',          cover = 'https://i.ytimg.com/vi/rOVsNCo_2d4/maxresdefault.jpg', title = 'Future - Life Is Good (Lyrics) ft. Drake' },
            { url = 'https://www.youtube.com/watch?v=goYgHnsQdtY', artist = 'POP SMOKE',           cover = 'https://i.ytimg.com/vi/goYgHnsQdtY/maxresdefault.jpg', title = 'Pop Smoke - Dior (Official Audio)' },
            { url = 'https://www.youtube.com/watch?v=qjKecb3pxuU', artist = 'POP SMOKE',           cover = 'https://i.ytimg.com/vi/qjKecb3pxuU/maxresdefault.jpg', title = 'POP SMOKE - WELCOME TO THE PARTY' },
            { url = 'https://www.youtube.com/watch?v=2-C2meu1BGg', artist = 'FutureHype',          cover = 'https://i.ytimg.com/vi/2-C2meu1BGg/maxresdefault.jpg', title = "Lil Yachty - Oprah's Bank Account (Lyrics) ft. DaBaby & Drake" },
            { url = 'https://www.youtube.com/watch?v=mjaayCARwro', artist = 'Kodak Black',         cover = 'https://i.ytimg.com/vi/mjaayCARwro/maxresdefault.jpg', title = 'Kodak Black - ZEZE (feat. Travis Scott & Offset) [Official Audio]' },
            { url = 'https://www.youtube.com/watch?v=m3HC1nyexwE', artist = 'Future - Topic',      cover = 'https://i.ytimg.com/vi/m3HC1nyexwE/maxresdefault.jpg', title = 'D4L' },
            { url = 'https://www.youtube.com/watch?v=Q5jnuOCJvK0', artist = 'DrakeVEVO',           cover = 'https://i.ytimg.com/vi/Q5jnuOCJvK0/maxresdefault.jpg', title = 'Drake - Pain 1993 (Audio) ft. Playboi Carti' },
            { url = 'https://www.youtube.com/watch?v=mx7oBDVL7Y4', artist = 'DrakeVEVO',           cover = 'https://i.ytimg.com/vi/mx7oBDVL7Y4/maxresdefault.jpg', title = 'Drake - Landed (Audio)' },
            { url = 'https://www.youtube.com/watch?v=Is3bH2mYmkU', artist = 'Meek Mill',           cover = 'https://i.ytimg.com/vi/Is3bH2mYmkU/maxresdefault.jpg', title = 'Meek Mill - On Me feat. Cardi B [Official Audio]' },
            { url = 'https://www.youtube.com/watch?v=OrGPt-Q-uOc', artist = 'Meek Mill',           cover = 'https://i.ytimg.com/vi/OrGPt-Q-uOc/maxresdefault.jpg', title = 'Meek Mill - Pay You Back feat. 21 Savage [Official Audio]' },
            { url = 'https://www.youtube.com/watch?v=JUnc3kl0DcA', artist = 'Meek Mill',           cover = 'https://i.ytimg.com/vi/JUnc3kl0DcA/maxresdefault.jpg', title = 'Meek Mill - Otherside of America [Official Audio]' },
            { url = 'https://www.youtube.com/watch?v=BHep3SgCplM', artist = 'Young Thug - Topic',  cover = 'https://i.ytimg.com/vi/BHep3SgCplM/maxresdefault.jpg', title = 'Hot (Remix) (feat. Gunna and Travis Scott)' },
            { url = 'https://www.youtube.com/watch?v=Z4reQmzuB4M', artist = 'TravisScottVEVO',     cover = 'https://i.ytimg.com/vi/Z4reQmzuB4M/maxresdefault.jpg', title = 'JACKBOYS, Travis Scott - OUT WEST (Audio) ft. Young Thug' },
            { url = 'https://www.youtube.com/watch?v=eJEKHdvntPI', artist = 'Megan Thee Stallion', cover = 'https://i.ytimg.com/vi/eJEKHdvntPI/maxresdefault.jpg', title = 'Megan Thee Stallion - Savage [Official Audio]' },
        },
    },
    {
        id = 'pop',
        name = 'Pop',
        accentClass = 'bg-cyan-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=EPo5wWmKEaI', artist = 'PitbullVEVO',         cover = 'https://i.ytimg.com/vi/EPo5wWmKEaI/maxresdefault.jpg', title = 'Pitbull - Give Me Everything ft. Ne-Yo, Afrojack, Nayer' },
            { url = 'https://www.youtube.com/watch?v=hHUbLv4ThOo', artist = 'PitbullVEVO',         cover = 'https://i.ytimg.com/vi/hHUbLv4ThOo/maxresdefault.jpg', title = 'Pitbull, Ke$ha - Timber (featuring Ke$ha - Official Video)' },
            { url = 'https://www.youtube.com/watch?v=e-fA-gBCkj0', artist = 'Bruno Mars',          cover = 'https://i.ytimg.com/vi/e-fA-gBCkj0/maxresdefault.jpg', title = 'Bruno Mars - Locked Out Of Heaven (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=uSD4vsh1zDA', artist = 'BlackEyedPeasVEVO',   cover = 'https://i.ytimg.com/vi/uSD4vsh1zDA/maxresdefault.jpg', title = 'The Black Eyed Peas - I Gotta Feeling (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=w4s6H4ku6ZY', artist = 'FarEastMovementVEVO', cover = 'https://i.ytimg.com/vi/w4s6H4ku6ZY/maxresdefault.jpg', title = 'Far East Movement - Like A G6 ft. The Cataracs, DEV' },
            { url = 'https://www.youtube.com/watch?v=t4H_Zoh7G5A', artist = 'JenniferLopezVEVO',   cover = 'https://i.ytimg.com/vi/t4H_Zoh7G5A/maxresdefault.jpg', title = 'Jennifer Lopez, Pitbull - On The Floor' },
            { url = 'https://www.youtube.com/watch?v=bpOR_HuHRNs', artist = 'Flo Rida',            cover = 'https://i.ytimg.com/vi/bpOR_HuHRNs/maxresdefault.jpg', title = 'Flo Rida - Wild Ones (feat Sia) [Official Video]' },
            { url = 'https://www.youtube.com/watch?v=88_iSSp5kXM', artist = 'David Guetta',        cover = 'https://i.ytimg.com/vi/88_iSSp5kXM/maxresdefault.jpg', title = 'David Guetta Feat. Akon - Sexy Chick (Official Video)' },
            { url = 'https://www.youtube.com/watch?v=6ACl8s_tBzE', artist = 'CalvinHarrisVEVO',    cover = 'https://i.ytimg.com/vi/6ACl8s_tBzE/maxresdefault.jpg', title = 'Calvin Harris - Blame ft. John Newman' },
            { url = 'https://www.youtube.com/watch?v=IcrbM1l_BoI', artist = 'AviciiOfficialVEVO',  cover = 'https://i.ytimg.com/vi/IcrbM1l_BoI/maxresdefault.jpg', title = 'Avicii - Wake Me Up (Official Video)' },
            { url = 'https://www.youtube.com/watch?v=OPf0YbXqDm0', artist = 'MarkRonsonVEVO',      cover = 'https://i.ytimg.com/vi/OPf0YbXqDm0/maxresdefault.jpg', title = 'Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars' },
            { url = 'https://www.youtube.com/watch?v=hT_nvWreIhg', artist = 'OneRepublicVEVO',     cover = 'https://i.ytimg.com/vi/hT_nvWreIhg/maxresdefault.jpg', title = 'OneRepublic - Counting Stars' },
            { url = 'https://www.youtube.com/watch?v=2zNSgSzhBfM', artist = 'Macklemore',          cover = 'https://i.ytimg.com/vi/2zNSgSzhBfM/maxresdefault.jpg', title = "MACKLEMORE & RYAN LEWIS - CAN'T HOLD US FEAT. RAY DALTON (OFFICIAL MUSIC VIDEO)" },
            { url = 'https://www.youtube.com/watch?v=QK8mJJJvaes', artist = 'Macklemore',          cover = 'https://i.ytimg.com/vi/QK8mJJJvaes/maxresdefault.jpg', title = 'MACKLEMORE & RYAN LEWIS - THRIFT SHOP FEAT. WANZ (OFFICIAL VIDEO)' },
            { url = 'https://www.youtube.com/watch?v=ItL6vcUrpUs', artist = 'Macklemore',          cover = 'https://i.ytimg.com/vi/ItL6vcUrpUs/maxresdefault.jpg', title = 'MACKLEMORE FEAT DAVE B & TRAVIS THOMPSON - CORNER STORE (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=7OrLroFa0AI', artist = 'Macklemore',          cover = 'https://i.ytimg.com/vi/7OrLroFa0AI/maxresdefault.jpg', title = 'MACKLEMORE FEAT SKYLAR GREY - GLORIOUS (OFFICIAL MUSIC VIDEO)' },
            { url = 'https://www.youtube.com/watch?v=bvC_0foemLY', artist = 'Robin Schulz',        cover = 'https://i.ytimg.com/vi/bvC_0foemLY/maxresdefault.jpg', title = 'Robin Schulz - Sugar (feat. Francesco Yates) (OFFICIAL MUSIC VIDEO)' },
            { url = 'https://www.youtube.com/watch?v=2Y6Nne8RvaA', artist = 'KungsVEVO',           cover = 'https://i.ytimg.com/vi/2Y6Nne8RvaA/maxresdefault.jpg', title = "Kungs vs Cookin' on 3 Burners - This Girl" },
            { url = 'https://www.youtube.com/watch?v=0XFudmaObLI', artist = 'TheSoundYouNeed',     cover = 'https://i.ytimg.com/vi/0XFudmaObLI/maxresdefault.jpg', title = 'Aaron Smith - Dancin (KRONO Remix)' },
            { url = 'https://www.youtube.com/watch?v=TGtWWb9emYI', artist = 'PitbullVEVO',         cover = 'https://i.ytimg.com/vi/TGtWWb9emYI/maxresdefault.jpg', title = 'We Are One (Ole Ola) [The Official 2014 FIFA World Cup Song] (Olodum Mix)' },
        },
    },
    {
        id = 'jazz',
        name = 'Jazz',
        accentClass = 'bg-amber-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=ZZcuSBouhVA', artist = 'MilesDavisVEVO', cover = 'https://i.ytimg.com/vi/ZZcuSBouhVA/default.jpg', title = 'Miles Davis - Freddie Freeloader (Audio) (Official Audio)' },
            { url = 'https://www.youtube.com/watch?v=vmDDOFXSgAs', artist = 'buckinny', cover = 'https://i.ytimg.com/vi/vmDDOFXSgAs/default.jpg', title = 'Dave Brubeck - Take Five' },
            { url = 'https://www.youtube.com/watch?v=ZrfzenYhv9w', artist = 'djbuddylovecooljazz', cover = 'https://i.ytimg.com/vi/ZrfzenYhv9w/default.jpg', title = 'So What - Miles Davis (1959)' },
            { url = 'https://www.youtube.com/watch?v=CWeXOm49kE0', artist = 'jazzhole13', cover = 'https://i.ytimg.com/vi/CWeXOm49kE0/default.jpg', title = 'Horace Silver - Song for My Father' },
            { url = 'https://www.youtube.com/watch?v=qJi03NqXfk8', artist = 'JazzTuna', cover = 'https://i.ytimg.com/vi/qJi03NqXfk8/default.jpg', title = 'Lee Morgan - The Sidewinder' },
            { url = 'https://www.youtube.com/watch?v=qWG2dsXV5HI', artist = 'Gnv123', cover = 'https://i.ytimg.com/vi/qWG2dsXV5HI/default.jpg', title = 'My Favorite Things - John Coltrane [FULL VERSION] HQ' },
            { url = 'https://www.youtube.com/watch?v=WqEweV0eScg', artist = 'Dustyologist II', cover = 'https://i.ytimg.com/vi/WqEweV0eScg/default.jpg', title = 'More Today Than Yesterday-Charles Earland-1970' },
            { url = 'https://www.youtube.com/watch?v=TDETNk20Vkc', artist = 'Nikos Krikelis', cover = 'https://i.ytimg.com/vi/TDETNk20Vkc/default.jpg', title = 'Kenny Dorham - Una mas' },
            { url = 'https://www.youtube.com/watch?v=xISaCzXYYg8', artist = '寶寶', cover = 'https://i.ytimg.com/vi/xISaCzXYYg8/default.jpg', title = "Art Pepper－You'd Be So Nice to Come Home To" },
            { url = 'https://www.youtube.com/watch?v=N76ErzOdk9g', artist = 'Santoszzz', cover = 'https://i.ytimg.com/vi/N76ErzOdk9g/default.jpg', title = 'Bud Powell - Collard Greens and Black Eyed Peas' },
            { url = 'https://www.youtube.com/watch?v=Cx-TxiBi43c', artist = 'magicoboninba', cover = 'https://i.ytimg.com/vi/Cx-TxiBi43c/default.jpg', title = 'Naima - John Coltrane' },
            { url = 'https://www.youtube.com/watch?v=zGsGwFBoEgc', artist = 'Unknown Artist', cover = 'https://i.ytimg.com/vi/zGsGwFBoEgc/default.jpg', title = 'Private video' },
            { url = 'https://www.youtube.com/watch?v=HmroWIcCNUI', artist = 'ConvertToMetal', cover = 'https://i.ytimg.com/vi/HmroWIcCNUI/default.jpg', title = 'Charlie "Bird" Parker - Yardbird Suite' },
            { url = 'https://www.youtube.com/watch?v=ujChUYkPvec', artist = 'Praguedive', cover = 'https://i.ytimg.com/vi/ujChUYkPvec/default.jpg', title = 'Thelonious Monk - Straight, No Chaser' },
            { url = 'https://www.youtube.com/watch?v=h6NCx0wcrC4', artist = 'JazzTuna', cover = 'https://i.ytimg.com/vi/h6NCx0wcrC4/default.jpg', title = 'John Coltrane - Giant Steps' },
            { url = 'https://www.youtube.com/watch?v=ECw3WAX41OA', artist = '60otaku4', cover = 'https://i.ytimg.com/vi/ECw3WAX41OA/default.jpg', title = 'Lee Morgan Quintet - Ceora' },
            { url = 'https://www.youtube.com/watch?v=I777BcgQL9o', artist = 'Sylvester R.', cover = 'https://i.ytimg.com/vi/I777BcgQL9o/default.jpg', title = 'Oliver Nelson - Stolen Moments' },
            { url = 'https://www.youtube.com/watch?v=yXK0pZx92MU', artist = 'J_Noodles', cover = 'https://i.ytimg.com/vi/yXK0pZx92MU/default.jpg', title = 'Charlie Parker- Confirmation' },
            { url = 'https://www.youtube.com/watch?v=jUN01HYwRX4', artist = 'rapitroy', cover = 'https://i.ytimg.com/vi/jUN01HYwRX4/default.jpg', title = 'Wynton Kelly Trio (Wes Montgomery)_ Unit 7' },
            { url = 'https://www.youtube.com/watch?v=KsAf0ra6Vd4', artist = 'Rico Jazz', cover = 'https://i.ytimg.com/vi/KsAf0ra6Vd4/default.jpg', title = 'Jimmy Smith - When Johnny Comes Marching Home' },
        },
    },
    {
        id = 'phonk',
        name = 'Phonk',
        accentClass = 'bg-lime-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=iFWzBZPs5uA', artist = 'Valence',          cover = 'https://i.ytimg.com/vi/iFWzBZPs5uA/maxresdefault.jpg', title = "Yb Wasg'ood, Ariis - LUNA BALA (Slowed)" },
            { url = 'https://www.youtube.com/watch?v=eeywSM0zAhY', artist = 'Valence',          cover = 'https://i.ytimg.com/vi/eeywSM0zAhY/maxresdefault.jpg', title = '2KE - PSL (Slowed)' },
            { url = 'https://www.youtube.com/watch?v=8dfeNOrVYCE', artist = 'Valence',          cover = 'https://i.ytimg.com/vi/8dfeNOrVYCE/maxresdefault.jpg', title = 'PASSO BEM SOLTO (Ultra Slowed)' },
            { url = 'https://www.youtube.com/watch?v=QRmcZhqlDoM', artist = 'Valence',          cover = 'https://i.ytimg.com/vi/QRmcZhqlDoM/maxresdefault.jpg', title = 'PASSO BEM SOLTO (Slowed)' },
            { url = 'https://www.youtube.com/watch?v=KoRe8U3oqYY', artist = 'Valence',          cover = 'https://i.ytimg.com/vi/KoRe8U3oqYY/maxresdefault.jpg', title = 'ATLXS - PASSO BEM SOLTO (Slowed)' },
            { url = 'https://www.youtube.com/watch?v=thzJu1ppV6o', artist = 'Valence',          cover = 'https://i.ytimg.com/vi/thzJu1ppV6o/maxresdefault.jpg', title = 'NAKAMA, MC STAFF - MENTE MA' },
            { url = 'https://www.youtube.com/watch?v=B9KFb_fmvV8', artist = 'TheGoodVibe',      cover = 'https://i.ytimg.com/vi/B9KFb_fmvV8/maxresdefault.jpg', title = 'MONTAGEM BAILAO' },
            { url = 'https://www.youtube.com/watch?v=rBdf-tgfDKE', artist = 'BROKE',            cover = 'https://i.ytimg.com/vi/rBdf-tgfDKE/maxresdefault.jpg', title = 'HISTED, TXVSTERPLAYA - MASHA ULTRAFUNK' },
            { url = 'https://www.youtube.com/watch?v=NvEKBcEa4uM', artist = 'Sayfalse - Topic', cover = 'https://i.ytimg.com/vi/NvEKBcEa4uM/maxresdefault.jpg', title = 'LOS VOLTAJE (Slowed)' },
            { url = 'https://www.youtube.com/watch?v=IttkO3cTfMI', artist = 'Jmilton - Topic',  cover = 'https://i.ytimg.com/vi/IttkO3cTfMI/maxresdefault.jpg', title = 'Montagem Bandido (Super Slowed)' },
            { url = 'https://www.youtube.com/watch?v=pUklUX8ITeo', artist = 'Dj Samir',         cover = 'https://i.ytimg.com/vi/pUklUX8ITeo/maxresdefault.jpg', title = 'MONTAGEM XONADA (Brazilian Funk + Phonk) MXZI, DJ SAMIR, DJ JAVI26' },
            { url = 'https://www.youtube.com/watch?v=TFizVLexsxU', artist = 'BROKE',            cover = 'https://i.ytimg.com/vi/TFizVLexsxU/maxresdefault.jpg', title = 'NCTS - NEXT!' },
            { url = 'https://www.youtube.com/watch?v=2cnloO84LA0', artist = 'Nakama',           cover = 'https://i.ytimg.com/vi/2cnloO84LA0/maxresdefault.jpg', title = 'DIA DELICIA - NAKAMA (Official Music Video)' },
            { url = 'https://www.youtube.com/watch?v=-vkI4_PN1I4', artist = 'Echope - Topic',   cover = 'https://i.ytimg.com/vi/-vkI4_PN1I4/maxresdefault.jpg', title = 'MONTAGEM SOLTO' },
            { url = 'https://www.youtube.com/watch?v=q5ncE4wIvfw', artist = 'Ogryzek - Topic',  cover = 'https://i.ytimg.com/vi/q5ncE4wIvfw/maxresdefault.jpg', title = 'GLORY' },
            { url = 'https://www.youtube.com/watch?v=jCExp0cfHJI', artist = 'void',             cover = 'https://i.ytimg.com/vi/jCExp0cfHJI/maxresdefault.jpg', title = 'Nakama, MC Gil Do Andarai - MONTAGEM MARE GRANA' },
            { url = 'https://www.youtube.com/watch?v=m97UHsMmcLs', artist = 'Valence',          cover = 'https://i.ytimg.com/vi/m97UHsMmcLs/maxresdefault.jpg', title = 'Dj Shazam Beat - MONTAGEM AMNESIA' },
            { url = 'https://www.youtube.com/watch?v=yU4dzYOAOAs', artist = 'Sayfalse - Topic', cover = 'https://i.ytimg.com/vi/yU4dzYOAOAs/maxresdefault.jpg', title = 'FUNK MI CAMINO' },
            { url = 'https://www.youtube.com/watch?v=43HK-seUbJs', artist = 'fennecxx - Topic', cover = 'https://i.ytimg.com/vi/43HK-seUbJs/maxresdefault.jpg', title = 'SPOOKY' },
            { url = 'https://www.youtube.com/watch?v=eEA4WNLcHNI', artist = 'The Vibe Guide',   cover = 'https://i.ytimg.com/vi/eEA4WNLcHNI/maxresdefault.jpg', title = 'MTG - RITMO ZELDA SUPER SLOWED' },
        },
    },
    {
        id = 'workout',
        name = 'Workout',
        accentClass = 'bg-red-500',
        tracks = {
            { url = 'https://www.youtube.com/watch?v=cnRB2CgUpSw', artist = 'Imagine Dragons - Topic',     cover = 'https://i.ytimg.com/vi/cnRB2CgUpSw/maxresdefault.jpg', title = 'Whatever It Takes' },
            { url = 'https://www.youtube.com/watch?v=pXu6JC6-d_o', artist = 'Imagine Dragons - Topic',     cover = 'https://i.ytimg.com/vi/pXu6JC6-d_o/maxresdefault.jpg', title = 'Natural' },
            { url = 'https://www.youtube.com/watch?v=dfk6i41GCNo', artist = 'Fall Out Boy - Topic',        cover = 'https://i.ytimg.com/vi/dfk6i41GCNo/maxresdefault.jpg', title = 'Centuries' },
            { url = 'https://www.youtube.com/watch?v=GXPRTZoIU1w', artist = 'Panic! At The Disco - Topic', cover = 'https://i.ytimg.com/vi/GXPRTZoIU1w/maxresdefault.jpg', title = 'Hey Look Ma, I Made It' },
            { url = 'https://www.youtube.com/watch?v=1uBPOu3si5w', artist = 'Imagine Dragons - Topic',     cover = 'https://i.ytimg.com/vi/1uBPOu3si5w/maxresdefault.jpg', title = 'Warriors' },
            { url = 'https://www.youtube.com/watch?v=6LUon6zLyTM', artist = 'Fall Out Boy - Topic',        cover = 'https://i.ytimg.com/vi/6LUon6zLyTM/maxresdefault.jpg', title = 'My Songs Know What You Did In The Dark (Light Em Up)' },
            { url = 'https://www.youtube.com/watch?v=W4C-NEWrnSQ', artist = 'Avicii - Topic',              cover = 'https://i.ytimg.com/vi/W4C-NEWrnSQ/maxresdefault.jpg', title = 'The Nights' },
            { url = 'https://www.youtube.com/watch?v=Q0TEUMPIhk8', artist = 'Coldplay - Topic',            cover = 'https://i.ytimg.com/vi/Q0TEUMPIhk8/maxresdefault.jpg', title = 'Paradise' },
            { url = 'https://www.youtube.com/watch?v=un6s1R-4Ud8', artist = 'Avicii - Topic',              cover = 'https://i.ytimg.com/vi/un6s1R-4Ud8/maxresdefault.jpg', title = 'Hey Brother' },
            { url = 'https://www.youtube.com/watch?v=e6vkFbtSGm0', artist = 'Fall Out Boy - Topic',        cover = 'https://i.ytimg.com/vi/e6vkFbtSGm0/maxresdefault.jpg', title = 'Immortals' },
            { url = 'https://www.youtube.com/watch?v=GJY8OMJXRAk', artist = 'Panic! At The Disco - Topic', cover = 'https://i.ytimg.com/vi/GJY8OMJXRAk/maxresdefault.jpg', title = 'High Hopes' },
            { url = 'https://www.youtube.com/watch?v=K9fISloOznc', artist = 'Avicii - Topic',              cover = 'https://i.ytimg.com/vi/K9fISloOznc/maxresdefault.jpg', title = 'Wake Me Up' },
            { url = 'https://www.youtube.com/watch?v=ZsHqUZTu2mY', artist = 'Panda Eyes - Topic',          cover = 'https://i.ytimg.com/vi/ZsHqUZTu2mY/maxresdefault.jpg', title = 'Highscore' },
            { url = 'https://www.youtube.com/watch?v=YHJVMELihGc', artist = 'The Score - Topic',           cover = 'https://i.ytimg.com/vi/YHJVMELihGc/maxresdefault.jpg', title = 'Unstoppable' },
            { url = 'https://www.youtube.com/watch?v=QJSfieToXSQ', artist = 'Bassment',                    cover = 'https://i.ytimg.com/vi/QJSfieToXSQ/maxresdefault.jpg', title = 'Lights - Ellie Goulding (Dubstep Remix) [HD]' },
            { url = 'https://www.youtube.com/watch?v=ZeaIvjoH1FY', artist = 'MrSuicideSheep',              cover = 'https://i.ytimg.com/vi/ZeaIvjoH1FY/maxresdefault.jpg', title = 'Flight Facilities - Crave You (Adventure Club Dubstep Remix) (feat. Giselle)' },
            { url = 'https://www.youtube.com/watch?v=YNQApdRY4CI', artist = 'Explodos',                    cover = 'https://i.ytimg.com/vi/YNQApdRY4CI/maxresdefault.jpg', title = 'Calvin Harris - Sweet Nothing (Diplo & Grandtheft Remix)' },
            { url = 'https://www.youtube.com/watch?v=YqeW9_5kURI', artist = 'Saskia',                      cover = 'https://i.ytimg.com/vi/YqeW9_5kURI/maxresdefault.jpg', title = 'Major Lazer & DJ snake Lean on Lyrics' },
        },
    },
} ]]
