--──────────────────────────────────────────────────────────────────────────────
-- Store Applications                                                          [EDIT]
-- [INFO] Apps available for download in the App Store.
--        Same base fields as PhoneApplications (including optional iframe).
--        job / minGrade / grades = Optional job access requirement (see PhoneApplications header).
--        sizeMb = app size in MB for simulated download progress.
--        creator, description, age, version, whatsNew, extraDescription = App Store detail (client-side UI).
--        price (optional) = premium app download price. If omitted/0, app is free.
--──────────────────────────────────────────────────────────────────────────────
Config.Store = Config.Store or {}
Config.Store.paymentAccounts = { 'money', 'bank' }

Config.StoreApps = {
    {
        id = 'pictagram',
        label = 'Pictagram',
        icon = 'pictagram.webp',
        category = 'Social',
        sizeMb = 580,
        creator = 'Pictagram Inc.',
        description = 'Share photos, videos, Reels and connect with friends and the world.',
        age = '16+',
        version = '2.4.1',
        whatsNew = 'Performance improvements, new creative tools, and bug fixes.',
        extraDescription = {
            {
                header = 'Share Moments and Explore Stories',
                head = 'Discover posts from people you follow',
                image = 'https://i.ibb.co/jvwvGX66/1.png',
                footer = 'Like, comment, and stay inspired',
            },
            {
                header = 'Stay Updated with Real-Time Notifications',
                head = 'See likes, comments, and new followers',
                image = 'https://i.ibb.co/Mk6My4dq/2.png',
                footer = 'Never miss what matters',
            },
            {
                header = 'Showcase Your Profile and Content',
                head = 'Display posts and grow your audience',
                image = 'https://i.ibb.co/6crr65nK/3.png',
                footer = 'Build your presence effortlessly',
            },
            {
                header = 'Edit and Personalize Your Profile',
                head = 'Update your info and details',
                image = 'https://i.ibb.co/KpYKhy8d/4.png',
                footer = 'Keep your profile fresh and relevant',
            },
            {
                header = 'Share Stories in a Visual Way',
                head = 'Post moments that disappear',
                image = 'https://i.ibb.co/DPdDjcCS/5.png',
                footer = 'Engage with your audience instantly',
            },
        },
    },
    {
        id = 'tweedle',
        label = 'Chirpy',
        icon = 'tweedle.webp',
        category = 'Social',
        sizeMb = 420,
        creator = 'Chirpy Inc.',
        description = 'Real-time conversations, trends, and community discussions.',
        age = '13+',
        version = '3.2.0',
        whatsNew = 'New trending system, improved notifications, and performance upgrades.',
        extraDescription = {
            {
                header = 'Stay Connected with Real-Time Posts',
                head = 'Discover what people are sharing now',
                image = 'https://i.ibb.co/nsCt9DRY/1.png',
                footer = 'Like, reply, and join the conversation',
            },
            {
                header = 'Personal Profiles Made Simple',
                head = 'View posts, media, and activity',
                image = 'https://i.ibb.co/Z6J8dFDK/2.png',
                footer = 'Manage your identity and connect easily',
            },
        },
    },
    {
        id = 'beatzy',
        label = 'Beatzy',
        icon = 'beatzy.webp',
        category = 'Social',
        sizeMb = 640,
        creator = 'Beatzy Inc.',
        description = 'Upload short videos, listen to music, and compete with friends.',
        age = '12+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Share Your Moments',
                head = 'Create and explore short videos',
                image = 'https://i.ibb.co/zh36H7Tj/1.png',
                footer = 'Engage with content and grow your audience',
            },
            {
                header = 'Experience Live Content',
                head = 'Watch and interact in real time',
                image = 'https://i.ibb.co/M3PmnN4/2.png',
                footer = 'Discover trending moments instantly',
            },
            {
                header = 'Showcase Your Profile',
                head = 'Display your content and stats',
                image = 'https://i.ibb.co/r273JR29/3.png',
                footer = 'Build your audience and stand out',
            },
        },
    },
    {
        id = 'chitchat',
        label = 'Whispr',
        icon = 'chitchat.webp',
        category = 'Social',
        sizeMb = 720,
        creator = 'Whispr Inc.',
        description = 'Instant messaging, voice and video calls with friends.',
        age = '16+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Whispr',
                head = 'Stay connected with the people who matter',
                image = 'https://i.ibb.co/dcPPG7h/chitchat.webp',
                footer = 'Chat, call, and create group conversations anytime, anywhere.',
            },
        },
    },
    {
        id = 'finder',
        label = 'Pairly',
        icon = 'finder.webp',
        category = 'Social',
        sizeMb = 480,
        creator = 'Pairly Inc.',
        description = 'Meet new people and find meaningful connections.',
        age = '18+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Swipe and Discover New Connections',
                head = 'Find people that match your vibe',
                image = 'https://i.ibb.co/KpBn7B3v/1.png',
                footer = 'Like or skip with a simple tap',
            },
            {
                header = 'It’s a Match — Start Connecting Instantly',
                head = 'See when the feeling is mutual',
                image = 'https://i.ibb.co/rLbnyL1/2.png',
                footer = 'Send a message and break the ice',
            },
            {
                header = 'Chat with Your Matches Anytime',
                head = 'All your conversations in one place',
                image = 'https://i.ibb.co/bRb4921T/3.png',
                footer = 'Stay connected and never miss a moment',
            },
            {
                header = 'Build and Customize Your Profile',
                head = 'Show who you are',
                image = 'https://i.ibb.co/tpjtcLKY/4.png',
                footer = 'Update your info and stand out',
            },
        },
    },
    {
        id = 'youlink',
        label = 'Media',
        icon = 'youlink.webp',
        category = 'Entertainment',
        sizeMb = 890,
        creator = 'Media Corp.',
        description = 'Watch videos, live streams, and trending content.',
        age = '8+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Discover Featured Media',
                head = 'Watch top clips curated for you',
                image = 'https://i.ibb.co/6R6Ncj7B/1.png',
                footer = 'Tap to play and enjoy trending content',
            },
        },
    },
    {
        id = 'yellowpages',
        label = 'Findly',
        icon = 'yellowpages.webp',
        category = 'Services',
        sizeMb = 280,
        creator = 'Los Santos Directory',
        description = 'Buy, sell, and discover local classifieds.',
        age = '18+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Browse Listings and Find Great Deals',
                head = 'Discover items posted near you',
                image = 'https://i.ibb.co/zHVNK0CM/1.png',
                footer = 'Search, explore, and connect instantly',
            },
            {
                header = 'View Detailed Listings with Ease',
                head = 'Check info, photos, and descriptions',
                image = 'https://i.ibb.co/215c6K7w/2.png',
                footer = 'Contact sellers in one tap',
            },
        },
    },
    {
        id = 'marketplace',
        label = 'Marketplace',
        icon = 'market.webp',
        category = 'Services',
        sizeMb = 365,
        creator = 'Los Santos Marketplace',
        description = 'Shop from the best local businesses in Los Santos.',
        age = '9+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Discover Nearby Shops',
                head = 'Explore businesses around you',
                image = 'https://i.ibb.co/HpVwFbV2/1.png',
                footer = 'Find services and visit stores easily',
            },
            {
                header = 'View Shop Details',
                head = 'Check ratings and contact options',
                image = 'https://i.ibb.co/99RdCbdT/2.png',
                footer = 'Navigate, message, or call instantly',
            },
        },
    },
    -- {
    --     id = 'icar',
    --     label = 'Garages',
    --     icon = 'garage.webp',
    --     category = 'Services',
    --     sizeMb = 310,
    --     creator = 'Los Santos DMV',
    --     description = 'Manage your vehicles and garages across the city.',
    --     age = '16+',
    --     version = '2.4.1',
    --     whatsNew = 'Performance improvements and bug fixes.',
    --     extraDescription = {
    --         {
    --             header = 'Manage All Your Vehicles in One Place',
    --             head = 'View garage status and locations',
    --             image = 'https://i.ibb.co/qFgKQCPm/1.png',
    --             footer = 'Track what’s in or out instantly',
    --         },
    --         {
    --             header = 'Detailed Vehicle Status at a Glance',
    --             head = 'Check engine, body, and fuel levels',
    --             image = 'https://i.ibb.co/prRsVCrs/2.png',
    --             footer = 'Call valet and manage with ease',
    --         },
    --     },
    -- },
    -- {
    --     id = 'aventon',
    --     label = 'Aventon',
    --     icon = 'rentel.webp',
    --     category = 'Services',
    --     sizeMb = 325,
    --     creator = 'Aventon Rentals',
    --     description = 'Rent premium vehicles instantly across Los Santos.',
    --     age = '16+',
    --     version = '2.4.1',
    --     whatsNew = 'Performance improvements and bug fixes.',
    --     extraDescription = {
    --         {
    --             header = 'Explore and Discover Vehicles Easily',
    --             head = 'Browse cars, bikes & SUVs',
    --             image = 'https://i.ibb.co/8Dg09qp1/1.png',
    --             footer = 'Fast, simple, all in one place',
    --         },
    --         {
    --             header = 'Rent Your Vehicle in Seconds',
    --             head = 'Check details & pricing instantly',
    --             image = 'https://i.ibb.co/sdYXKzJT/2.png',
    --             footer = 'Book your ride with one tap',
    --         },
    --     },
    -- },
    {
        id = 'zapp',
        label = 'Zapp',
        icon = 'zapp.webp',
        category = 'Services',
        sizeMb = 295,
        creator = 'Zapp Technologies',
        description = 'Request rides or earn money as a driver.',
        age = '18+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Request a Ride in Seconds',
                head = 'Choose your ride and nearby driver',
                image = 'https://i.ibb.co/Q3ymfVpK/1.png',
                footer = 'Fast, simple, and reliable trips',
            },
            {
                header = 'Start Driving and Earning Easily',
                head = 'Set your rates and go online',
                image = 'https://i.ibb.co/ZRrksrFj/2.png',
                footer = 'Turn your time into income',
            },
            {
                header = 'Track Trips and Earnings Clearly',
                head = 'Monitor your activity and stats',
                image = 'https://i.ibb.co/1fG064KT/3.png',
                footer = 'Stay on top of your performance',
            },
        },
    },
    {
        id = 'zappeats',
        label = 'Zapp Eats',
        icon = 'zappeats.webp',
        category = 'Services',
        sizeMb = 275,
        creator = 'Zapp Technologies',
        description = 'Order food delivery or earn as a courier.',
        age = '6+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Manage Your Deliveries at a Glance',
                head = 'Track performance and recent activity',
                image = 'https://i.ibb.co/q3Lq0GR3/1.png',
                footer = 'Stay efficient and maximize your results',
            },
            {
                header = 'Work Live on the Map',
                head = 'Accept orders and manage your shift',
                image = 'https://i.ibb.co/ZRLKMW2r/2.png',
                footer = 'Stay active and deliver with ease',
            },
        },
    },
    -- {
    --     id = 'jobcenter',
    --     label = 'Job Center',
    --     icon = 'jobcenter.webp',
    --     category = 'Services',
    --     sizeMb = 245,
    --     creator = 'Los Santos Jobs',
    --     description = 'Discover job opportunities across the city.',
    --     age = '18+',
    --     version = '2.4.1',
    --     whatsNew = 'Performance improvements and bug fixes.',
    --     extraDescription = {
    --         {
    --             header = 'Choose Your Job',
    --             head = 'Browse available roles and start working',
    --             image = 'https://i.ibb.co/s9BmM0bk/1.png',
    --             footer = 'Pick a job and get started instantly',
    --         },
    --     },
    -- },
    -- {
    --     id = 'onionbrowser',
    --     label = 'Onion Browser',
    --     icon = 'onionbrowser.webp',
    --     category = 'Utilities',
    --     price = 550,
    --     sizeMb = 520,
    --     creator = 'Thor Networks',
    --     description = 'Anonymous browsing for the deep web.',
    --     age = '18+',
    --     version = '2.4.1',
    --     whatsNew = 'Performance improvements and bug fixes.',
    --     extraDescription = {
    --         {
    --             header = 'Secure and Private Marketplace Access',
    --             head = 'Browse items with full anonymity',
    --             image = 'https://i.ibb.co/JjWJqSPf/1.png',
    --             footer = 'Stay hidden while you shop',
    --         },
    --         {
    --             header = 'Encrypted Chats and Private Channels',
    --             head = 'Communicate safely in dark mode',
    --             image = 'https://i.ibb.co/QvhZbTNb/2.png',
    --             footer = 'Your messages, fully protected',
    --         },
    --         {
    --             header = 'Real-Time Anonymous Messaging Experience',
    --             head = 'Send and receive messages instantly',
    --             image = 'https://i.ibb.co/KHYZxpY/3.png',
    --             footer = 'Stay connected without revealing identity',
    --         },
    --         {
    --             header = 'Customize Your Anonymous Profile Easily',
    --             head = 'Manage your identity and settings',
    --             image = 'https://i.ibb.co/j9fjzQNP/4.png',
    --             footer = 'Stay private, stay in control',
    --         },
    --     },
    -- },
    {
        id = 'darkchat',
        label = 'Dark Chat',
        icon = 'darkchat.webp',
        category = 'Utilities',
        price = 250,
        sizeMb = 265,
        creator = 'Anon Systems',
        description = 'Completely private and untraceable messaging.',
        age = '18+',
        version = '2.4.1',
        whatsNew = 'Performance improvements and bug fixes.',
        extraDescription = {
            {
                header = 'Dark Chat',
                head = 'Talk without fear',
                image = 'https://i.ibb.co/K2qznvW/darkchat.png',
                footer = 'Decentralized encrypted chats. No logs. No tracking.',
            },
        },
    },
    {
        id = 'fruitchop',
        label = 'Slice Rush',
        icon = 'fruitchop.webp',
        category = 'Games',
        sizeMb = 680,
        creator = 'Quasar Games',
        description = 'Fast-paced fruit slicing action game.',
        age = '3+',
        isGame = true,
        iframe = {
            url = 'https://cdn-factory.marketjs.com/en/fruit-slice-frenzy/index.html',
            rotate = true,
            phoneRotate = true,
            css = {
                width = '215%',
                height = '50%',
                transform = 'rotate(90deg)',
                border = 'none',
                position = 'absolute',
                left = '-60%',
                top = '25%',
            },
        },
        extraDescription = {
            {
                header = 'Combo Frenzy',
                head = 'Slice and chain combos',
                image = 'https://i.ibb.co/DfXh2QMH/2.png',
                footer = 'Keep the streak alive',
            },
            {
                header = 'Slice Master',
                head = 'More points, more speed',
                image = 'https://i.ibb.co/qMNf4sRz/1.png',
                footer = 'Don’t hit the bomb',
            },
        },
    },
    {
        id = 'chikenblast',
        label = 'Chick Blast',
        icon = 'chikenblast.webp',
        category = 'Games',
        sizeMb = 745,
        creator = 'Quasar Games',
        description = 'Colorful and fun chicken collecting puzzle game.',
        age = '6+',
        isGame = true,
        iframe = {
            url = 'https://cdn-factory.marketjs.com/en/chicken-blast/index.html',
            rotate = true,
            phoneRotate = true,
            css = {
                width = '215%',
                height = '50%',
                transform = 'rotate(90deg)',
                border = 'none',
                position = 'absolute',
                left = '-60%',
                top = '25%',
            },
        },
        extraDescription = {
            {
                header = 'Mega Combo',
                head = 'Match fast, score big',
                image = 'https://i.ibb.co/hRQphZGv/1.png',
                footer = 'Keep chaining',
            },
            {
                header = 'Clear the Grid',
                head = 'Break blocks, unlock space',
                image = 'https://i.ibb.co/FkfFnV5g/2.png',
                footer = 'Think before you tap',
            },
            {
                header = 'Combo Boost',
                head = 'Bigger matches, higher score',
                image = 'https://i.ibb.co/fdtKBJpM/3.png',
                footer = 'Don’t miss the chain',
            },
        },
    },
    {
        id = 'kingkongracing',
        label = 'Turbo Kart',
        icon = 'kingkongracing.webp',
        category = 'Games',
        -- price = 900,
        sizeMb = 715,
        creator = 'Quasar Games',
        description = 'High-speed kart racing with monkeys.',
        age = '3+',
        isGame = true,
        iframe = {
            url = 'https://cdn-factory.marketjs.com/en/king-kong-kart-racing/index.html',
            rotate = true,
            phoneRotate = true,
            css = {
                width = '215%',
                height = '50%',
                transform = 'rotate(90deg)',
                border = 'none',
                position = 'absolute',
                left = '-60%',
                top = '25%',
            },
        },
        extraDescription = {
            {
                header = 'Speed Run',
                head = 'Drift fast, go further',
                image = 'https://i.ibb.co/yBfJxVmg/imagen-2026-04-22-140341269.png',
                footer = 'Beat your best distance',
            },
        },
    },
    {
        id = 'mmacitybrawl',
        label = 'Street Fight',
        icon = 'mmacitybrawl.webp',
        category = 'Games',
        -- price = 900,
        sizeMb = 820,
        creator = 'Quasar Games',
        description = 'Intense street fighting and brawling action.',
        age = '18+',
        isGame = true,
        iframe = {
            url = 'https://cdn-factory.marketjs.com/en/mma-city-brawl/index.html',
            rotate = true,
            phoneRotate = true,
            css = {
                width = '215%',
                height = '50%',
                transform = 'rotate(90deg)',
                border = 'none',
                position = 'absolute',
                left = '-60%',
                top = '25%',
            },
        },
        extraDescription = {
            {
                header = 'First Hit',
                head = 'Strike fast, stay sharp',
                image = 'https://i.ibb.co/FLWsKM6z/1.png',
                footer = 'Don’t lose momentum',
            },
            {
                header = 'Knockdown',
                head = 'Time your attacks right',
                image = 'https://i.ibb.co/dsxsHVYP/2.png',
                footer = 'Finish the fight',
            },
        },
    },
    {
        id = 'tunelace',
        label = 'Void Drift',
        icon = 'tunelace.webp',
        category = 'Games',
        price = 300,
        sizeMb = 780,
        creator = 'Quasar Games',
        description = 'Fast arcade runner. Dodge obstacles and survive longer.',
        age = '3+',
        isGame = true,
        iframe = {
            url = 'https://cdn-factory.marketjs.com/en/tunnel-ace/index.html',
            rotate = true,
            phoneRotate = true,
            css = {
                width = '225%',
                height = '48%',
                transform = 'rotate(90deg)',
                border = 'none',
                position = 'absolute',
                left = '-62%',
                top = '26%',
            },
        },
        extraDescription = {
            {
                header = 'Deep Run',
                head = 'Fly steady, dodge fast',
                image = 'https://i.ibb.co/yF6Nnbz4/1.png',
                footer = 'Stay in control',
            },
            {
                header = 'Sharp Turn',
                head = 'React quick, avoid impact',
                image = 'https://i.ibb.co/PGthMvQZ/2.png',
                footer = 'One mistake ends it',
            },
            {
                header = 'Final Escape',
                head = 'Speed up, survive longer',
                image = 'https://i.ibb.co/wF9ZHPMp/3.png',
                footer = 'Push your limit',
            },
        },

    },
    {
        id = 'rescueship',
        label = 'Rescue Fleet',
        icon = 'rescueship.webp',
        category = 'Games',
        sizeMb = 760,
        creator = 'Quasar Games',
        description = 'Rescue sailors. Navigate and survive.',
        age = '3+',
        isGame = true,
        iframe = {
            url = 'https://cdn-factory.marketjs.com/en/rescue-ship-race-against-time/index.html',
            rotate = true,
            phoneRotate = true,
            css = {
                width = '225%',
                height = '48%',
                transform = 'rotate(90deg)',
                border = 'none',
                position = 'absolute',
                left = '-62%',
                top = '26%',
            },
        },
        extraDescription = {
            {
                header = 'Mission Start',
                head = 'Sail out, save them',
                image = 'https://i.ibb.co/ZPsN8YK/1.png',
                footer = 'Every life counts',
            },
            {
                header = 'Full Rescue',
                head = 'Reach them all in time',
                image = 'https://i.ibb.co/FkdRVzhP/2.png',
                footer = 'Be the hero at sea',
            },
        },

    },
    {
        id = 'driftboss',
        label = 'Drift Track',
        icon = 'driftboss.webp',
        category = 'Games',
        price = 190,
        sizeMb = 795,
        creator = 'Quasar Games',
        description = 'Rescue sailors. Navigate and survive.',
        age = '3+',
        isGame = true,
        iframe = {
            url = 'https://cdn-consumer.marketjs.com/game/drift-boss-advanced/',
            rotate = true,
            phoneRotate = true,
            css = {
                width = '225%',
                height = '48%',
                transform = 'rotate(90deg)',
                border = 'none',
                position = 'absolute',
                left = '-62%',
                top = '26%',
            },
        },
        extraDescription = {
            {
                header = 'Start Drift',
                head = 'Slide clean, stay on track',
                image = 'https://i.ibb.co/5xY2fT0R/1.png',
                footer = 'Control the drift',
            },
            {
                header = 'Sharp Turn',
                head = 'Master every corner',
                image = 'https://i.ibb.co/JFBR7VQz/2.png',
                footer = 'Don’t fall off',
            },
        },

    },
}
