Config.Tips = {
    categories = {
        { id = 'basics',        title = 'Basics',                subtitle = 'Turn on, navigate, and essentials', icon = 'f7:phone_fill' },
        { id = 'communication', title = 'Calls & Messages',      subtitle = 'Stay in touch',                     icon = 'f7:chat_bubble_2_fill' },
        { id = 'media',         title = 'Photos & Camera',       subtitle = 'Capture and browse',                icon = 'f7:camera_fill' },
        { id = 'productivity',  title = 'Productivity',          subtitle = 'Mail, notes, reminders',            icon = 'f7:square_list_fill' },
        { id = 'privacy',       title = 'Privacy & Settings',    subtitle = 'Control your phone',                icon = 'f7:lock_fill' },
        { id = 'social',        title = 'Social Apps',           subtitle = 'Connect, share & chat',             icon = 'f7:person_2_fill' },
        { id = 'entertainment', title = 'Entertainment & Games', subtitle = 'Media, music, videos & play',       icon = 'f7:play_circle_fill' },
        { id = 'services',      title = 'Services',              subtitle = 'Rides, jobs & marketplace',         icon = 'f7:briefcase_fill' },
        { id = 'utilities',     title = 'Utilities',             subtitle = 'Tools & advanced apps',             icon = 'f7:hammer_fill' },
    },
    slideGroups = {
        {
            categoryId = 'basics',
            slides = {
                {
                    id = 'wake',
                    title = 'Wake your phone',
                    body = 'Press the side button on the right edge of your device to instantly light up the screen and see the lock screen with the time, date, notifications, and widgets at a glance. From any app you can swipe up from the very bottom edge of the screen to return to the home screen instantly. This gesture works everywhere and is the fastest way to navigate without ever getting lost in menus.',
                    icon = 'f7:power',
                    order = 1,
                },
                {
                    id = 'home',
                    title = 'Home screen',
                    body = 'All your installed apps are organized across multiple pages that you can swipe left or right to browse. Simply tap any app icon to launch it immediately. Press and hold any icon for a moment to enter edit mode where you can drag apps around to rearrange them, create folders by dropping one app on top of another, or remove apps you no longer need by tapping the small minus sign. You can also use the mouse scroll wheel while on the home screen to quickly pull down and view all your notifications at a glance. Furthermore, if you press and hold the click directly on the time shown in the status bar at the top of the screen, you will open the full customization menu allowing you to change colors, themes, wallpaper, and personalize the entire look of your home screen exactly how you want.',
                    icon = 'f7:square_grid_2x2_fill',
                    order = 2,
                },
                {
                    id = 'control',
                    title = 'Quick controls',
                    body = 'Swipe down from the top-right corner of the screen to open Control Center and instantly adjust brightness, volume, Wi-Fi, Bluetooth, airplane mode, and many other shortcuts without opening any apps. Double-click the side button or swipe up from the bottom and pause to open the app switcher, letting you jump between your most recently used apps with a quick swipe or close them by swiping up on their preview.',
                    icon = 'f7:slider_horizontal_3',
                    order = 3,
                },
                {
                    id = 'notifications',
                    title = 'Notifications',
                    body = 'Pull down from the top of the screen to open the Notification Center and see all your alerts grouped by app. You can swipe left on any notification to quickly reply, mark as read, or manage settings for that specific app. Long-press a notification to expand it and see more details or interactive buttons directly from the lock screen or home screen.',
                    icon = 'f7:bell_fill',
                    order = 4,
                },
                {
                    id = 'lockscreen',
                    title = 'Lock screen',
                    body = 'Swipe up from the bottom of the lock screen to unlock using your passcode or Face ID when available. Customize your lock screen with widgets for weather, calendar events, battery level, and more so you get useful information without even unlocking the phone. Tap the flashlight icon in the bottom-left or the camera icon in the bottom-right for instant access to those tools from the lock screen.',
                    icon = 'f7:lock_shield_fill',
                    order = 5,
                },
                {
                    id = 'weather',
                    title = 'Weather',
                    body = 'Open the Weather app to see current temperature, conditions, feels-like temperature, and an hourly breakdown for the next 24 hours plus a full 7-day forecast. Tap any city in your list to switch locations instantly or add new cities by searching. Scroll down for detailed information including UV index, wind speed, humidity, sunrise and sunset times so you can plan your day perfectly.',
                    icon = 'f7:cloud_sun_fill',
                    order = 6,
                },
                {
                    id = 'calendar',
                    title = 'Calendar',
                    body = 'The Calendar app is not a fully usable or interactive application like the others. Its only purpose is to display the current day and date directly on the app icon itself, showing the actual day of the month (for example "27") and the abbreviated weekday (like "MON") updated in real time. Tapping the icon does nothing extra and simply returns you to the home screen because there is no full interface, no event list, no reminders, and no way to add appointments.',
                    icon = 'f7:calendar',
                    order = 7,
                },
                {
                    id = 'map',
                    title = 'Maps',
                    body = 'Search for any address, business, or landmark and get turn-by-turn directions with real-time traffic updates and estimated arrival time. Tap the map to drop a pin and save favorite locations for one-tap navigation later. Switch between driving, walking, transit, or cycling modes and see alternative routes. The app also shows nearby points of interest like restaurants, gas stations, and parking.',
                    icon = 'f7:map_fill',
                    order = 8,
                },
            },
        },
        {
            categoryId = 'communication',
            slides = {
                {
                    id = 'phone_app',
                    title = 'Phone',
                    body = 'Launch the Phone app to dial any number using the keypad, review your recent calls with details like duration and time, or listen to voicemail messages. Add important contacts to Favorites for one-tap calling directly from the home screen or widget. You can also block unwanted numbers, create groups, and set custom ringtones or text tones for each contact so you always know who is calling or messaging you.',
                    icon = 'f7:phone_fill',
                    order = 1,
                },
                {
                    id = 'messages',
                    title = 'Messages',
                    body = 'Use the Messages app to send and receive SMS-style texts, photos, videos, voice messages, and your current location in real time. Conversations are automatically threaded so you can easily scroll back through the entire history and stay organized. Tap the camera icon inside any chat to quickly snap and send a photo or video without leaving the conversation.',
                    icon = 'f7:chat_bubble_fill',
                    order = 2,
                },
                {
                    id = 'videocall',
                    title = 'Video calls',
                    body = 'Start a high-quality face-to-face video call directly from the Phone or Messages app when you want to see the person you are talking to. Great for business meetings, family catch-ups, or showing something in real time. During the call you can switch between front and rear cameras, mute your microphone, or share your screen if needed. The call works over Wi-Fi or mobile data.',
                    icon = 'f7:videocam_fill',
                    order = 3,
                },
                {
                    id = 'contacts',
                    title = 'Contacts',
                    body = 'The Contacts app stores all your friends, family, and colleagues with phone numbers, emails, addresses, birthdays, notes, and even profile photos. Use the powerful search bar at the top to find anyone instantly. Add new contacts manually or import them from other accounts. You can also assign ringtone and text tone preferences per contact and create smart groups for quick messaging or calling.',
                    icon = 'f7:person_fill',
                    order = 4,
                },
            },
        },
        {
            categoryId = 'media',
            slides = {
                {
                    id = 'camera',
                    title = 'Camera',
                    body = 'Open the Camera app and swipe between different modes including Photo, Video, Portrait, Panorama, and more. Pinch to zoom in or out, tap the screen to lock focus and exposure, or use the volume buttons as a shutter if you prefer. Record videos in high resolution and switch between front and rear cameras instantly. All your shots are automatically saved to the Gallery for easy browsing and editing later.',
                    icon = 'f7:camera_fill',
                    order = 1,
                },
                {
                    id = 'gallery',
                    title = 'Gallery',
                    body = 'Browse all your photos and videos organized into albums, moments, or by date in the Gallery app. Pinch with two fingers to zoom in on any image or video for a closer look. Tap the share button to send pictures directly to Messages, social apps, or other devices. You can also create new albums, favorite important shots, and delete unwanted items to keep everything clean and organized.',
                    icon = 'f7:photo_fill',
                    order = 2,
                },
                {
                    id = 'music',
                    title = 'Music',
                    body = 'Play your personal music library, create custom playlists, or stream songs and podcasts directly in the Music app. Control playback from the lock screen, Control Center, or even while using other apps. The app remembers your listening history and suggests new music based on what you enjoy. You can also download songs for offline listening so your music is always available even without internet.',
                    icon = 'f7:music_note_2',
                    order = 3,
                },
                {
                    id = 'health',
                    title = 'Health',
                    body = 'Track your daily steps, workouts, heart rate, sleep, and many other health metrics all in one place inside the Health app. Set personal fitness goals and receive encouraging updates when you hit them. View beautiful charts and trends over time to see your progress. The app can also integrate data from other fitness trackers and smartwatches for a complete picture of your wellbeing.',
                    icon = 'f7:heart_fill',
                    order = 4,
                },
            },
        },
        {
            categoryId = 'productivity',
            slides = {
                {
                    id = 'mail',
                    title = 'Mail',
                    body = 'The Mail app gives you a unified inbox for all your email accounts including your personal @cloud address. Swipe left or right on any message to quickly archive, delete, reply, or flag it for later. Tap the compose button to write a new email with attachments, formatting, and even signatures. Search through thousands of messages instantly and organize everything with folders and smart mailboxes.',
                    icon = 'f7:envelope_fill',
                    order = 1,
                },
                {
                    id = 'notes',
                    title = 'Notes',
                    body = 'Quickly jot down ideas, create detailed checklists, draw sketches with your finger, or scan documents directly inside the Notes app. Everything is searchable across all your notes so you can find any text or image in seconds. Organize notes into folders and share them with others for real-time collaboration. Password-protect sensitive notes to keep your private thoughts secure.',
                    icon = 'f7:doc_text_fill',
                    order = 2,
                },
                {
                    id = 'reminders',
                    title = 'Reminders',
                    body = 'Create smart lists and set due dates and times for every task so nothing slips through the cracks in the Reminders app. Enable location-based reminders that notify you when you arrive at or leave a certain place. The app supports Siri voice commands so you can add reminders hands-free. Check off completed tasks and see a beautiful daily summary of what you need to do.',
                    icon = 'f7:checkmark_circle_fill',
                    order = 3,
                },
                {
                    id = 'wallet',
                    title = 'Wallet',
                    body = 'Store credit cards, debit cards, transit passes, tickets, and loyalty cards securely in the Wallet app. Double-click the side button to bring up Wallet from the lock screen for fast contactless payments. Add boarding passes or event tickets so they appear automatically on the right day. The app keeps everything encrypted and protected with Face ID or passcode.',
                    icon = 'f7:wallet_fill',
                    order = 4,
                },
                {
                    id = 'crypto',
                    title = 'Crypto',
                    body = 'Monitor your cryptocurrency balances, send and receive coins, and view live price charts and market trends right inside the Crypto app. Set price alerts so you never miss a big movement. The app uses secure encryption and biometric authentication to keep your wallet completely safe. Track multiple different coins and view detailed transaction history at any time.',
                    icon = 'f7:bitcoin_circle_fill',
                    order = 5,
                },
                {
                    id = 'calculator',
                    title = 'Calculator',
                    body = 'Switch between basic and scientific calculator modes depending on what you need. The app remembers your last calculation and lets you swipe to delete the last digit or clear everything instantly. Use memory functions to store and recall numbers during complex calculations. Rotate your phone to landscape for an even more powerful scientific layout with advanced functions.',
                    icon = 'f7:plus_slash_minus',
                    order = 6,
                },
            },
        },
        {
            categoryId = 'privacy',
            slides = {
                {
                    id = 'settings',
                    title = 'Settings',
                    body = 'The Settings app is the central hub where you can customize almost everything about your phone including display brightness, sounds and haptics, wallpaper, notifications, and much more. Scroll through the list to find specific sections for each system feature or installed app. Everything that shapes how your device looks and behaves lives here in one convenient place.',
                    icon = 'f7:gear_alt_fill',
                    order = 1,
                },
                {
                    id = 'passcode',
                    title = 'Security',
                    body = 'Set up a strong passcode and enable Face ID when available to keep your personal data completely protected. The phone will automatically lock after a short period of inactivity and require authentication to unlock. All your sensitive information stays securely on the device unless you explicitly choose to share it with an app or another person.',
                    icon = 'f7:lock_fill',
                    order = 2,
                },
                {
                    id = 'display_custom',
                    title = 'Display & Customization',
                    body = 'Go to Settings → Display & Brightness to fine-tune how your screen looks and performs. You can remove the blur effect entirely for significantly better performance and smoother animations across all apps. Change the phone prop color and the frame color to give your device a completely personalized look that matches your style and mood.',
                    icon = 'f7:display',
                    order = 3,
                },
                {
                    id = 'notifications_privacy',
                    title = 'Notification privacy',
                    body = 'Decide exactly which apps are allowed to send you notifications and whether they can appear on your lock screen, banner, or notification center. Turn off notifications for specific apps when you need total focus or silence. You can also schedule a focus mode that automatically silences everything except the people and apps you choose during certain hours.',
                    icon = 'f7:bell_slash_fill',
                    order = 4,
                },
                {
                    id = 'app_permissions',
                    title = 'App permissions',
                    body = 'Review and control exactly which apps have access to your camera, microphone, location, contacts, photos, and other private data. You can grant permission only while the app is in use or revoke it completely at any time. The Settings app shows you a clear list of every permission granted so you stay in full control of your privacy.',
                    icon = 'f7:shield_fill',
                    order = 5,
                },
            },
        },
        {
            categoryId = 'social',
            slides = {
                {
                    id = 'pictagram',
                    title = 'Pictagram',
                    body = 'Share your best photos and videos, create Reels, and connect with friends and the whole world through Pictagram. Browse the feed to discover posts from people you follow, like, comment, and get inspired by creative content. Build your audience by posting regularly and using the built-in editing tools to make your profile stand out.',
                    icon = 'f7:photo_fill',
                    order = 1,
                },
                {
                    id = 'chirpy',
                    title = 'Chirpy',
                    body = 'Join real-time conversations, follow the latest trends, and participate in community discussions with Chirpy. See what people are talking about right now, reply to posts, and build your own following. The app keeps you updated with instant notifications so you never miss important moments or trending topics in your network.',
                    icon = 'f7:chat_bubble_text_fill',
                    order = 2,
                },
                {
                    id = 'beatzy',
                    title = 'Beatzy',
                    body = 'Upload short videos, listen to trending music, compete with friends in challenges, and discover live content in Beatzy. Showcase your personality through creative clips and grow your audience while having fun. The app makes it easy to interact with videos in real time and see who is watching your content right now.',
                    icon = 'f7:play_rectangle_fill',
                    order = 3,
                },
                {
                    id = 'whispr',
                    title = 'Whispr',
                    body = 'Send instant text messages, make crystal-clear voice calls, or start video calls with friends and groups in Whispr. Create private or public group chats that stay organized and easy to follow. The app works seamlessly over Wi-Fi or mobile data so you can stay connected with the people who matter most no matter where you are.',
                    icon = 'f7:chat_bubble_fill',
                    order = 4,
                },
                {
                    id = 'pairly',
                    title = 'Pairly',
                    body = 'Meet new people who match your vibe by swiping through profiles in Pairly. When you get a match you can start chatting immediately and see shared interests. Customize your profile with photos and details to stand out and build meaningful connections in a safe and fun environment.',
                    icon = 'f7:heart_fill',
                    order = 5,
                },
            },
        },
        {
            categoryId = 'entertainment',
            slides = {
                {
                    id = 'youlink',
                    title = 'Media',
                    body = 'Discover and watch an endless stream of videos, live broadcasts, and trending content tailored just for you in the Media app. Tap on featured clips to play them instantly and enjoy high-quality playback with easy controls for volume, speed, and subtitles. Save your favorite videos to watch later or share them directly with friends through other apps.',
                    icon = 'f7:play_fill',
                    order = 1,
                },
                {
                    id = 'weazel',
                    title = 'News',
                    body = 'Stay completely up to date with the latest news and stories happening across Los Santos and beyond through the Weazel News app. Read full articles, watch video reports, and get push notifications for breaking events. Customize your feed so you only see the topics that interest you most and never miss important local updates.',
                    icon = 'f7:newspaper_fill',
                    order = 2,
                },
                {
                    id = 'music',
                    title = 'Music',
                    body = 'Play your personal music library, create custom playlists, or stream songs and podcasts directly in the Music app. Control playback from the lock screen, Control Center, or even while using other apps. The app remembers your listening history and suggests new music based on what you enjoy. You can also download songs for offline listening so your music is always available even without internet.',
                    icon = 'f7:music_note_2',
                    order = 3,
                },
                {
                    id = 'fruitchop',
                    title = 'Slice Rush',
                    body = 'Enjoy fast-paced fruit slicing action in Slice Rush where you swipe to cut as many fruits as possible while avoiding dangerous bombs. Chain combos together to multiply your score and unlock higher levels with increasing speed and difficulty. The game is perfect for short bursts of fun and helps improve your reflexes and hand-eye coordination.',
                    icon = 'f7:gamecontroller_fill',
                    order = 4,
                },
                {
                    id = 'chikenblast',
                    title = 'Chick Blast',
                    body = 'Match colorful chickens in this addictive puzzle game to create huge combos and clear the entire grid. Plan your moves carefully to maximize points and unlock special power-ups that help you blast through tough levels. The bright visuals and satisfying sound effects make every match feel rewarding and keep you coming back for more.',
                    icon = 'f7:gamecontroller_fill',
                    order = 5,
                },
                {
                    id = 'kingkongracing',
                    title = 'Turbo Kart',
                    body = 'Race at high speed in Turbo Kart with fun monkey characters while mastering drifts around every corner to gain extra boost. Beat your own best distance records and unlock new tracks and vehicles as you progress. The responsive controls and vibrant graphics make every race exciting and competitive.',
                    icon = 'f7:gamecontroller_fill',
                    order = 6,
                },
                {
                    id = 'mmacitybrawl',
                    title = 'Street Fight',
                    body = 'Jump into intense street fighting action in Street Fight where precise timing and combos determine who wins each brawl. Learn different attack patterns, block incoming hits, and finish your opponents with powerful special moves. The game rewards skill and quick reactions as you climb the leaderboards.',
                    icon = 'f7:gamecontroller_fill',
                    order = 7,
                },
                {
                    id = 'tunelace',
                    title = 'Void Drift',
                    body = 'Test your reflexes in Void Drift, a fast-paced endless runner where you fly through a futuristic tunnel dodging obstacles at increasing speeds. React quickly to sharp turns and collect power-ups to extend your run and achieve new high scores. The smooth controls and neon visuals create an immersive arcade experience.',
                    icon = 'f7:gamecontroller_fill',
                    order = 8,
                },
                {
                    id = 'rescueship',
                    title = 'Rescue Fleet',
                    body = 'Take command of a rescue fleet and navigate dangerous waters to save sailors in time in Rescue Fleet. Plan your route carefully, avoid hazards, and reach every target before it is too late. The game combines strategy and quick thinking with beautiful ocean visuals and satisfying rescue animations.',
                    icon = 'f7:gamecontroller_fill',
                    order = 9,
                },
                {
                    id = 'driftboss',
                    title = 'Drift Track',
                    body = 'Master the art of drifting around every corner in Drift Track while keeping perfect control of your car. Learn the best lines through each track and push your limits to set new personal records. The realistic physics and responsive steering make every successful drift feel incredibly satisfying.',
                    icon = 'f7:gamecontroller_fill',
                    order = 10,
                },
            },
        },
        {
            categoryId = 'services',
            slides = {
                {
                    id = 'findly',
                    title = 'Findly',
                    body = 'Browse thousands of local classified ads for buying, selling, and trading items right in your city with Findly. Filter by category, price, or location to find exactly what you need and contact sellers with one tap. Post your own listings with photos and descriptions to sell items quickly and safely.',
                    icon = 'f7:tag_fill',
                    order = 1,
                },
                {
                    id = 'marketplace',
                    title = 'Marketplace',
                    body = 'Discover and shop from the best local businesses and stores in Los Santos through the Marketplace app. View detailed shop information, ratings, photos, and contact options all in one place. Get directions, message the owner, or call instantly to place orders or schedule services.',
                    icon = 'f7:cart_fill',
                    order = 2,
                },
                -- {
                --     id = 'garages',
                --     title = 'Garages',
                --     body = 'Manage every vehicle you own across all your garages in the city with iCar. Check real-time status, fuel levels, engine health, and location of each car. Call a valet service directly from the app or move vehicles between properties with just a few taps.',
                --     icon = 'f7:car_fill',
                --     order = 3,
                -- },
                -- {
                --     id = 'aventon',
                --     title = 'Aventon',
                --     body = 'Rent premium cars, bikes, and SUVs instantly across Los Santos with Aventon. Browse available vehicles with full details and pricing, then book your ride in seconds. The app shows you exactly where the vehicle is located and guides you through the entire rental process.',
                --     icon = 'f7:car_fill',
                --     order = 4,
                -- },
                {
                    id = 'zapp',
                    title = 'Zapp',
                    body = 'Request a ride in seconds or become a driver and earn money with Zapp. Track your current trip live on the map, see driver arrival time, and pay securely through the app. Drivers can set their own rates, go online whenever they want, and monitor earnings and performance statistics.',
                    icon = 'f7:car_fill',
                    order = 5,
                },
                {
                    id = 'zappeats',
                    title = 'Zapp Eats',
                    body = 'Order food from your favorite restaurants and have it delivered quickly with Zapp Eats. Track your order in real time from preparation to delivery. Couriers can accept orders, navigate with the built-in map, and manage their entire shift while earning money on their own schedule.',
                    icon = 'f7:bag_fill',
                    order = 6,
                },
                -- {
                --     id = 'jobcenter',
                --     title = 'Job Center',
                --     body = 'Browse dozens of available job opportunities across the entire city and start working immediately through the Job Center app. Each listing shows requirements, pay rate, and location so you can choose the perfect role. Apply with one tap and begin earning right away.',
                --     icon = 'f7:briefcase_fill',
                --     order = 7,
                -- },
            },
        },
        {
            categoryId = 'utilities',
            slides = {
                -- {
                --     id = 'onionbrowser',
                --     title = 'Onion Browser',
                --     body = 'Browse the deep web completely anonymously and access secure marketplaces and private channels with Onion Browser. All your traffic is routed through multiple encrypted layers so your identity stays hidden. The app includes built-in tools for encrypted messaging and profile management while keeping you fully protected.',
                --     icon = 'f7:shield_fill',
                --     order = 1,
                -- },
                {
                    id = 'darkchat',
                    title = 'Dark Chat',
                    body = 'Send completely private and untraceable messages with Dark Chat. The decentralized system uses end-to-end encryption with no logs or tracking of any kind. Create group chats or private channels and communicate safely even when you need total anonymity.',
                    icon = 'f7:lock_fill',
                    order = 2,
                },
                {
                    id = 'store',
                    title = 'App Store',
                    body = 'Browse thousands of apps, check their size, version history, and what’s new before downloading them in the App Store. Read descriptions and view screenshots to make sure each app is right for you. Updates are delivered automatically so you always have the latest features and security fixes.',
                    icon = 'f7:app_fill',
                    order = 3,
                },
                -- {
                --     id = 'houses',
                --     title = 'Home',
                --     body = 'View and manage all your owned properties and their attached garages from anywhere in the city with the Home app. See real-time status of each house, transfer ownership, or check vehicle storage. The app gives you a complete overview of your real estate portfolio at a glance.',
                --     icon = 'f7:house_fill',
                --     order = 4,
                -- },
            },
        },
    },
}
