Config = Config or {}

Config.Debug = false

Config.Commands = {
    enabled = true,
    tutorial = 'tutorial',
    guide = 'guia',
}

Config.Tutorial = {
    enabled = true,
    openOnce = true,
    progressScope = 'license',
    metadataKey = 'ob_initial_completed',
    autoOpenAfterCharacter = true,
    openDelay = 1800,
    preCharacterDelay = 250,
    totalPages = 8,
    slides = {
        {
            id = 'welcome',
            type = 'welcome',
            eyebrow = 'ANTES DE COMEÇARMOS',
            title = 'Seja bem-vindo à Obscuria',
            text = 'Eu sou Lucien. Antes de você cruzar estas portas, preciso lhe mostrar como este mundo respira.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            character = 'assets/characters/vampire-guide.png',
            characterSide = 'left',
            topics = {
                {
                    title = 'Classes',
                    text = 'Bruxas, Vampiros, Curandeiras e Humanos encontram caminhos diferentes dentro da mesma cidade.',
                },
                {
                    title = 'Lideranças',
                    text = 'Cada grupo possui vozes, regras e responsabilidades próprias. Reconhecê-las faz parte da sua história.',
                },
                {
                    title = 'Poderes',
                    text = 'Habilidades sobrenaturais têm propósito, custo e consequência. Saber quando não usá-las também é poder.',
                },
            },
            noteTitle = 'Sobre os Humanos',
            note = 'Humanos não possuem poderes sobrenaturais. Ainda assim, preparo, tecnologia, alianças e versatilidade fazem deles uma escolha longe de ser inferior.',
        },
        {
            id = 'classes',
            type = 'classes',
            eyebrow = 'LIÇÃO I',
            title = 'Escolha o seu caminho',
            text = 'As três naturezas sobrenaturais oferecem forças muito diferentes, e nenhuma delas existe sem consequência.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            characterSide = 'left',
            classTabs = {
                {
                    id = 'vampire',
                    label = 'Vampiro',
                    color = '#b83a4e',
                    tabImage = 'assets/characters/lucien-present.png',
                    character = 'assets/characters/lucien-present.png',
                    epithet = 'Predadores entre luz e escuridão',
                    summary = 'Imortais moldados pela magia, Vampiros unem força, velocidade e domínio mental. Sua conexão com as trevas permite controlar sombras, mudar de forma e sobreviver onde outros cairiam.',
                    strengths = {
                        'Força e velocidade sobre-humanas',
                        'Metamorfose e mobilidade aérea',
                        'Controle mental e drenagem vital',
                    },
                    weaknessTitle = 'A Fome Eterna',
                    weakness = 'Todo esse poder exige essência vital. Sem se alimentar, o Vampiro perde força, controle e lucidez; quanto mais cede à fome, mais difícil se torna satisfazê-la sem ser consumido por ela.',
                },
                {
                    id = 'healer',
                    label = 'Curandeira',
                    color = '#4f9f72',
                    tabImage = 'assets/characters/class-healer.png',
                    character = 'assets/characters/class-healer.png',
                    epithet = 'Guardiãs do equilíbrio vital',
                    summary = 'Curandeiras restauram corpo e espírito, interrompem ferimentos e preservam a tênue fronteira entre vida e morte. Seu poder floresce quando elas e o ambiente permanecem em harmonia.',
                    strengths = {
                        'Cura e regeneração profundas',
                        'Suporte, serenidade e voo',
                        'Proteção da vida e do equilíbrio',
                    },
                    weaknessTitle = 'O Custo da Cura',
                    weakness = 'Curar em excesso cobra a vitalidade da própria Curandeira. Exaustão emocional, esforço contínuo e ambientes corrompidos enfraquecem seus dons e podem fazê-la adoecer ou envelhecer antes do tempo.',
                },
                {
                    id = 'witch',
                    label = 'Bruxa',
                    color = '#8662b7',
                    tabImage = 'assets/characters/class-witch.png',
                    character = 'assets/characters/class-witch.png',
                    epithet = 'Mestras do conhecimento arcano',
                    summary = 'Bruxas dominam feitiços, encantamentos e forças elementais. Sua maior vantagem é a versatilidade: conhecimento e preparo permitem alterar circunstâncias que pareciam inevitáveis.',
                    strengths = {
                        'Feitiçaria e encantamentos versáteis',
                        'Manipulação de forças elementais',
                        'Percepção e vínculos arcanos',
                    },
                    weaknessTitle = 'Os Ecos da Magia',
                    weakness = 'Todo feitiço deixa um eco na alma e no mundo. Magias intensas ampliam o desgaste físico e mental, podem escapar ao controle e ainda deixam rastros perceptíveis para quem sabe caçá-los.',
                },
            },
        },
        {
            id = 'essences',
            type = 'essence',
            eyebrow = 'LIÇÃO II',
            title = 'A energia de cada classe',
            text = 'A essência é a reserva que sustenta manifestações sobrenaturais. Cada natureza possui uma cor, um ritmo e um propósito.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            character = 'assets/characters/lucien-book.png',
            characterSide = 'right',
            humanNote = 'Humanos não geram nem consomem essência sobrenatural.',
            classTabs = {
                {
                    id = 'vampire',
                    label = 'Vampiro',
                    essence = 'Essência Carmesim',
                    color = '#b83a4e',
                    image = 'assets/essence/vampire.png',
                    purpose = 'Impulso, metamorfose e domínio',
                    description = 'A essência dos Vampiros é intensa e predatória. Ela sustenta movimentos sobre-humanos, mudanças de forma e habilidades de influência.',
                    guidance = 'Administrá-la significa escolher entre velocidade, sobrevivência e controle do alvo.',
                },
                {
                    id = 'healer',
                    label = 'Curandeira',
                    essence = 'Essência Vital',
                    color = '#4f9f72',
                    image = 'assets/essence/healer.png',
                    purpose = 'Cuidado, equilíbrio e mobilidade',
                    description = 'A energia das Curandeiras acompanha a vida. Ela alimenta curas, alívio de condições e o voo por meio de asas etéreas.',
                    guidance = 'Seu valor está na constância: preservar alguém pode mudar toda uma história.',
                },
                {
                    id = 'witch',
                    label = 'Bruxa',
                    essence = 'Essência Arcana',
                    color = '#8662b7',
                    image = 'assets/essence/witch.png',
                    purpose = 'Percepção, vínculo e feitiçaria',
                    description = 'A essência das Bruxas responde ao conhecimento e à intenção. Ela sustenta dons naturais e a magia canalizada pelo grimório e pela varinha.',
                    guidance = 'Usar magia deixa resquícios. Outra Bruxa atenta pode encontrar o caminho que você percorreu.',
                },
            },
        },
        {
            id = 'powers',
            type = 'powers',
            eyebrow = 'LIÇÃO III',
            title = 'Poderes de classe',
            text = 'Cada habilidade ocupa um papel específico. Passe o cursor sobre um poder para conhecer sua função antes de depender dele.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            character = 'assets/characters/lucien-present.png',
            characterSide = 'left',
            classTabs = {
                {
                    id = 'vampire',
                    label = 'Vampiro',
                    color = '#b83a4e',
                    image = 'assets/essence/vampire.png',
                    tabImage = 'assets/characters/lucien-present.png',
                    character = 'assets/characters/lucien-present.png',
                    powers = {
                        { label = 'Passo Sombrio', icon = 'assets/powers/vampire/icons/passo-sombrio.png', description = 'Velocidade sobre-humana, salto ampliado e deslocamento envolto em sombras.' },
                        { label = 'Forma de Morcego', icon = 'assets/powers/vampire/icons/forma-morcego.png', description = 'Assume uma forma alada pequena para voar e escapar sem atacar.' },
                        { label = 'Hipnose', icon = 'assets/powers/vampire/icons/hipnose.png', description = 'Projeta uma onda mental que paralisa e confunde o primeiro alvo atingido.' },
                        { label = 'Abraço da Noite', icon = 'assets/powers/vampire/icons/abraco-da-noite.png', description = 'Drena a energia vital de um alvo próximo para restaurar vida e essência.' },
                    },
                },
                {
                    id = 'healer',
                    label = 'Curandeira',
                    color = '#4f9f72',
                    image = 'assets/essence/healer.png',
                    tabImage = 'assets/characters/class-healer.png',
                    character = 'assets/characters/class-healer.png',
                    powers = {
                        { label = 'Voo', icon = 'assets/powers/healer/icons/voo.png', description = 'Manifesta asas etéreas e permite explorar os céus livremente.' },
                        { label = 'Cura Vital', icon = 'assets/powers/healer/icons/cura-vital.png', description = 'Restaura gradualmente os próprios ferimentos ou os de outro ser.' },
                        { label = 'Serenidade', icon = 'assets/powers/healer/icons/serenidade.png', description = 'Dissipa estresse, medo, ansiedade e exaustão do alvo.' },
                        { label = 'Estancar Sangramento', icon = 'assets/powers/healer/icons/estancar-sangramento.png', description = 'Interrompe hemorragias por meio de regeneração acelerada.' },
                    },
                },
                {
                    id = 'witch',
                    label = 'Bruxa',
                    color = '#8662b7',
                    image = 'assets/essence/witch.png',
                    tabImage = 'assets/characters/class-witch.png',
                    character = 'assets/characters/class-witch.png',
                    powers = {
                        { label = 'Familiar', icon = 'assets/powers/witch/icons/familiar.png', description = 'Assume a forma de um gato preto, pequena, discreta e incapaz de combater.' },
                        { label = 'Sentido Arcano', icon = 'assets/powers/witch/icons/sentido-arcano.png', description = 'Revela resquícios de essência e sinais recentes de atividade sobrenatural.' },
                        { label = 'Elo Arcano', icon = 'assets/powers/witch/icons/elo-arcano.png', description = 'Canaliza energia para recuperar a própria essência ou a de um aliado.' },
                        { label = 'Névoa das Bruxas', icon = 'assets/powers/witch/icons/nevoa-das-bruxas.png', description = 'Invoca uma névoa densa para ocultar fugas e o uso de feitiços.' },
                    },
                },
            },
        },
        {
            id = 'society',
            type = 'society',
            eyebrow = 'LIÇÃO IV',
            title = 'Viver entre os outros',
            text = 'Obscuria não é formada apenas por poderes. Reputação, alianças e respeito às lideranças determinam quais portas permanecerão abertas para você.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            character = 'assets/characters/lucien-present.png',
            characterSide = 'right',
            representatives = {
                { label = 'Vampiros', role = 'Casas, pactos e domínio', color = '#b83a4e', image = 'assets/characters/lucien-present.png' },
                { label = 'Curandeiras', role = 'Cuidado e equilíbrio', color = '#4f9f72', image = 'assets/characters/class-healer.png' },
                { label = 'Bruxas', role = 'Tradição e conhecimento', color = '#8662b7', image = 'assets/characters/class-witch.png' },
                { label = 'Humanos', role = 'Ofícios e instituições', color = '#9a7848', image = 'assets/characters/class-human.png' },
            },
            principles = {
                { index = '01', title = 'Reconheça as lideranças', text = 'Cada grupo possui representantes, regras internas e responsabilidades. Ouvir antes de agir evita conflitos desnecessários.' },
                { index = '02', title = 'Construa alianças', text = 'Nenhuma classe resolve tudo sozinha. Relações bem cuidadas abrem acesso a informação, proteção e oportunidades.' },
                { index = '03', title = 'Aceite as consequências', text = 'Favores, crimes e traições deixam memória. Sua reputação muda a forma como a cidade responde à sua presença.' },
            },
            noteTitle = 'A cidade observa',
            note = 'Poder impõe presença; postura constrói influência. Escolha com cuidado quem saberá o seu nome.',
        },
        {
            id = 'human_path',
            type = 'human',
            eyebrow = 'LIÇÃO V',
            title = 'O valor de ser Humano',
            text = 'Humanos não canalizam essência e não conjuram poderes. Em troca, seguem um caminho livre de fome, ecos mágicos e custos sobrenaturais.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            character = 'assets/characters/class-human.png',
            characterSide = 'left',
            paths = {
                { index = '01', title = 'Investigação', text = 'Observe padrões, reúna provas e descubra fraquezas antes de enfrentar aquilo que não compreende.' },
                { index = '02', title = 'Tecnologia', text = 'Ferramentas, veículos, sistemas de segurança e equipamentos especiais substituem a força sobrenatural.' },
                { index = '03', title = 'Versatilidade', text = 'Profissões, alianças e preparo permitem ocupar funções que nenhuma criatura consegue manter sem levantar suspeitas.' },
            },
            advantageTitle = 'Sem essência. Não sem recursos.',
            advantage = 'O Humano vence pela informação, planejamento e liberdade para escolher sua função. É uma classe especialmente forte para investigação, negócios, segurança e histórias de superação.',
            warning = 'Você não terá uma habilidade sobrenatural para corrigir uma decisão ruim. Em compensação, também não carregará a fraqueza que acompanha cada dom.',
        },
        {
            id = 'progression',
            type = 'progression',
            eyebrow = 'LIÇÃO VI',
            title = 'Construa o seu caminho',
            text = 'Seu personagem não nasce pronto. Conhecimento, equipamentos e relações transformam potencial em domínio.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            character = 'assets/characters/lucien-book.png',
            characterSide = 'right',
            steps = {
                { index = '01', title = 'Descubra', text = 'Explore a cidade, conheça pessoas e encontre oportunidades que não aparecem no mapa.' },
                { index = '02', title = 'Aprenda', text = 'Livros de aprendizado liberam feitiços do grimório. Poder sem estudo continuará inacessível.' },
                { index = '03', title = 'Equipe', text = 'Varinhas, acessórios e itens de classe ampliam possibilidades e preparam você para situações específicas.' },
                { index = '04', title = 'Domine', text = 'Pratique, administre recursos e escolha quando revelar suas capacidades. Experiência vale mais que pressa.' },
            },
            essentials = {
                { label = 'Livros', text = 'Desbloqueiam novos conhecimentos.' },
                { label = 'Grimório', text = 'Organiza os feitiços da Bruxa.' },
                { label = 'Equipamentos', text = 'Alteram preparo e possibilidades.' },
                { label = 'Reputação', text = 'Muda oportunidades e relações.' },
            },
        },
        {
            id = 'first_steps',
            type = 'journey',
            eyebrow = 'LIÇÃO VII',
            title = 'Seu primeiro passo',
            text = 'Trabalhos constroem sua vida; atividades ilegais colocam tudo em risco. Em Obscuria, até o mesmo roubo se transforma conforme a natureza de quem o executa.',
            speaker = 'Lucien',
            background = 'assets/backgrounds/academy-entry.png',
            characterSide = 'left',
            classTabs = {
                {
                    id = 'vampire',
                    label = 'Vampiro',
                    color = '#b83a4e',
                    tabImage = 'assets/characters/lucien-present.png',
                    character = 'assets/characters/lucien-present.png',
                    role = 'Velocidade, influência e atuação noturna',
                    legalTitle = 'Onde pode prosperar',
                    legal = 'Segurança, transporte, investigações noturnas e trabalhos que recompensam presença, mobilidade e resistência.',
                    illegalTitle = 'Como viola um sistema',
                    illegal = 'Segue circuitos como veias, conduzindo uma linha de sangue até o ponto que força máquinas e cofres a expulsarem o conteúdo.',
                    phases = {
                        { title = 'Acesso', text = 'Percebe o pulso correto da fechadura.' },
                        { title = 'Cofre', text = 'Conecta os canais de sangue do mecanismo.' },
                        { title = 'Retirada', text = 'Drena a proteção e libera o dinheiro.' },
                    },
                },
                {
                    id = 'healer',
                    label = 'Curandeira',
                    color = '#4f9f72',
                    tabImage = 'assets/characters/class-healer.png',
                    character = 'assets/characters/class-healer.png',
                    role = 'Cuidado, natureza e sustentação do grupo',
                    legalTitle = 'Onde pode prosperar',
                    legal = 'Medicina, resgate, botânica e suporte a grupos que dependem de estabilidade, recuperação e deslocamento aéreo.',
                    illegalTitle = 'Como viola um sistema',
                    illegal = 'Faz raízes percorrerem frestas e mecanismos. Vinhas pressionam travas, envolvem compartimentos e puxam o dinheiro para fora.',
                    phases = {
                        { title = 'Acesso', text = 'Cultiva o trajeto correto entre as travas.' },
                        { title = 'Cofre', text = 'Memoriza e harmoniza os núcleos vitais.' },
                        { title = 'Retirada', text = 'Comanda vinhas para recolher o conteúdo.' },
                    },
                },
                {
                    id = 'witch',
                    label = 'Bruxa',
                    color = '#8662b7',
                    tabImage = 'assets/characters/class-witch.png',
                    character = 'assets/characters/class-witch.png',
                    role = 'Runas, conhecimento e corrupção arcana',
                    legalTitle = 'Onde pode prosperar',
                    legal = 'Pesquisa, investigação sobrenatural, criação de itens e trabalhos que exigem leitura de resíduos mágicos.',
                    illegalTitle = 'Como viola um sistema',
                    illegal = 'Escreve runas para corromper a segurança. Depois do ritual, canaliza magia à distância para romper o compartimento.',
                    phases = {
                        { title = 'Acesso', text = 'Traça a runa sem abandonar o desenho.' },
                        { title = 'Cofre', text = 'Escuta e alinha ressonâncias arcanas.' },
                        { title = 'Retirada', text = 'Rompe o núcleo e espalha o dinheiro.' },
                    },
                },
                {
                    id = 'human',
                    label = 'Humano',
                    color = '#9a7848',
                    tabImage = 'assets/characters/class-human.png',
                    character = 'assets/characters/class-human.png',
                    role = 'Ferramentas, estratégia e discrição',
                    legalTitle = 'Onde pode prosperar',
                    legal = 'Pode seguir qualquer profissão comum: mecânica, polícia, negócios, transporte, tecnologia ou investigação.',
                    illegalTitle = 'Como viola um sistema',
                    illegal = 'Compensa a ausência de magia com hacking, ferramentas de precisão e planejamento. Não consome essência, mas depende do equipamento certo.',
                    phases = {
                        { title = 'Acesso', text = 'Manipula a fechadura com ferramentas.' },
                        { title = 'Cofre', text = 'Decifra a segurança eletrônica e mecânica.' },
                        { title = 'Retirada', text = 'Organiza a coleta sem deixar evidências.' },
                    },
                },
            },
            warning = 'Falhar não encerra necessariamente a tentativa, mas pode consumir recursos, deixar rastros e alertar a polícia. Quanto maior o roubo, mais etapas e consequências existirão.',
            choices = {
                { id = 'review_classes', label = 'Rever as classes', action = 'goto', target = 2 },
                { id = 'begin', label = 'Começar minha jornada', action = 'complete', primary = true },
            },
        },
    },
}

Config.Guide = {
    enabled = true,
    name = 'Edward',
    model = 'ig_bankman',
    coords = vec4(-940.85, -385.03, 39.0, 24.39),
    scenario = 'WORLD_HUMAN_CLIPBOARD',
    interactionDistance = 2.2,
    spawnDistance = 80.0,
    despawnDistance = 120.0,
    targetLabel = 'Conversar com Edward',
    targetIcon = 'fa-solid fa-bell-concierge',
    starterVehicle = {
        enabled = true,
        once = true,
        metadataKey = 'ob_initial_starter_vehicle',
        model = 'prairie',
        garage = 'motelgarage',
        platePrefix = 'OB',
    },
    slides = {
        {
            id = 'guide_welcome',
            type = 'guide',
            eyebrow = 'HOTEL RAVENWOOD',
            title = 'Em que posso ajudá-lo(a)?',
            text = 'Bem-vindo(a) ao Hotel Ravenwood. Espero que sua viagem até Obscuria tenha sido tranquila.',
            paragraphs = {
                'Meu nome é Edward. Trabalho aqui auxiliando os recém-chegados a encontrarem seu lugar na cidade.',
                'Obscuria pode parecer um pouco diferente à primeira vista, mas garanto que logo você se acostuma.',
            },
            speaker = 'Edward · Concierge do Hotel Ravenwood',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            choices = {
                { id = 'city', label = 'Quero conhecer a cidade', action = 'goto', target = 2 },
                { id = 'job', label = 'Preciso de um emprego', action = 'goto', target = 3 },
                { id = 'vehicle', label = 'Onde consigo um veículo?', action = 'goto', target = 4 },
                { id = 'tips', label = 'Tem alguma dica para iniciantes?', action = 'goto', target = 5 },
                { id = 'obscuria', label = 'O que é Obscuria?', action = 'goto', target = 6 },
                { id = 'leave', label = 'Nada, obrigado', action = 'goto', target = 7 },
            },
        },
        {
            id = 'guide_city',
            type = 'guide',
            eyebrow = 'ORIENTAÇÃO · A CIDADE',
            title = 'Conheça Obscuria',
            text = 'Obscuria tem muito a oferecer, e você não vai precisar andar sem rumo.',
            paragraphs = {
                'No seu mapa estão marcados praticamente todos os locais importantes da cidade: comércios, empregos, lojas, oficinas mecânicas, hospital, salões de beleza e diversos outros serviços essenciais.',
                'Além disso, a cidade recebe eventos especiais todas as semanas. Sempre que um evento estiver acontecendo, ele aparecerá destacado no mapa com uma marcação diferente, facilitando encontrá-lo.',
                'Aliás, hoje você chegou em um ótimo dia. Está acontecendo a inauguração do Parque de Diversões. Se ainda não sabe por onde começar sua aventura, eu diria para passar por lá. Além de conhecer outros moradores, você pode aproveitar o evento e sentir como é a vida em Obscuria.',
                'Há mais alguma coisa que gostaria de saber?',
            },
            speaker = 'Edward',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            choices = {
                { id = 'back', label = 'Voltar às opções', action = 'goto', target = 1, primary = true },
                { id = 'leave', label = 'Encerrar conversa', action = 'goto', target = 7 },
            },
        },
        {
            id = 'guide_job',
            type = 'guide',
            eyebrow = 'ORIENTAÇÃO · TRABALHO',
            title = 'Seu primeiro emprego',
            text = 'Todo mundo começa de algum lugar. Se pretende construir uma boa vida em Obscuria, o trabalho é sempre o primeiro passo.',
            paragraphs = {
                'Você pode procurar uma oportunidade na Central de Empregos, que está marcada no seu mapa. Lá encontrará mais de 25 profissões diferentes, cada uma com suas próprias funções e remunerações.',
                'Mas não se limite a isso. Muitos estabelecimentos da cidade contratam funcionários diretamente. Basta visitar o local e conversar com o gerente. Nunca se sabe quando alguém estará precisando de uma boa pessoa para integrar a equipe.',
                'Com dedicação, logo você estará construindo sua própria história por aqui. Posso ajudar com mais alguma coisa?',
            },
            speaker = 'Edward',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            calloutTitle = 'Central de Empregos',
            callout = 'Consulte o mapa para encontrar as vagas públicas. Estabelecimentos particulares podem contratar diretamente.',
            choices = {
                { id = 'back', label = 'Voltar às opções', action = 'goto', target = 1, primary = true },
                { id = 'leave', label = 'Encerrar conversa', action = 'goto', target = 7 },
            },
        },
        {
            id = 'guide_vehicle',
            type = 'guide',
            eyebrow = 'ORIENTAÇÃO · TRANSPORTE',
            title = 'Um começo sobre rodas',
            text = 'Um dos meus papéis aqui no Hotel é garantir que todo recém-chegado tenha como dar seus primeiros passos pela cidade.',
            paragraphs = {
                'Tenho um veículo reservado em seu nome, pronto para ser retirado. Com ele, será muito mais fácil conhecer Obscuria, chegar aos empregos e participar dos eventos espalhados pela cidade.',
                'Gostaria de retirar seu primeiro veículo agora?',
            },
            speaker = 'Edward',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            calloutTitle = 'Veículo de boas-vindas',
            callout = 'O veículo será registrado em seu nome e enviado à garagem configurada. A retirada é permitida somente uma vez.',
            choices = {
                { id = 'claim_vehicle', label = 'Sim, registrar meu veículo', action = 'starterVehicle', target = 8, primary = true },
                { id = 'later', label = 'Não, depois eu volto', action = 'goto', target = 1 },
            },
        },
        {
            id = 'guide_tips',
            type = 'guide',
            eyebrow = 'ORIENTAÇÃO · PRIMEIROS PASSOS',
            title = 'Alguns conselhos',
            text = 'Algumas, na verdade.',
            bullets = {
                'Converse com as pessoas.',
                'Não tenha medo de fazer perguntas.',
                'Trabalhe antes de gastar.',
                'Respeite as leis da cidade.',
                'Aproveite sua história. Obscuria recompensa quem cria boas memórias.',
            },
            speaker = 'Edward',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            choices = {
                { id = 'back', label = 'Voltar às opções', action = 'goto', target = 1, primary = true },
                { id = 'leave', label = 'Encerrar conversa', action = 'goto', target = 7 },
            },
        },
        {
            id = 'guide_obscuria',
            type = 'guide',
            eyebrow = 'ORIENTAÇÃO · A VERDADE',
            title = 'O que é Obscuria?',
            text = 'Uma cidade como qualquer outra... pelo menos é o que muitos acreditam.',
            paragraphs = {
                'Alguns moradores juram que coisas impossíveis acontecem por aqui. Outros dizem que são apenas lendas.',
                'Seja qual for a verdade, Obscuria sempre muda aqueles que escolhem permanecer.',
            },
            speaker = 'Edward',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            choices = {
                { id = 'back', label = 'Voltar às opções', action = 'goto', target = 1, primary = true },
                { id = 'leave', label = 'Encerrar conversa', action = 'goto', target = 7 },
            },
        },
        {
            id = 'guide_farewell',
            type = 'guide',
            eyebrow = 'HOTEL RAVENWOOD',
            title = 'Até breve',
            text = 'Foi um prazer ajudá-lo(a). As portas do Hotel Ravenwood estarão sempre abertas para você.',
            paragraphs = {
                'Sempre que acordar e passar por aqui, venha conversar comigo. Todos os dias posso mantê-lo(a) atualizado(a) sobre o que aconteceu em Obscuria enquanto esteve ausente, avisar sobre eventos que estão acontecendo ou ainda vão acontecer e compartilhar outras informações que podem ser úteis para a sua jornada.',
                'Nunca se sabe quando uma boa oportunidade pode surgir. Tenha um ótimo dia, e seja bem-vindo(a) à sua nova vida em Obscuria.',
            },
            speaker = 'Edward',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            choices = {
                { id = 'close', label = 'Encerrar conversa', action = 'close', primary = true },
            },
        },
        {
            id = 'guide_vehicle_ready',
            type = 'guide',
            eyebrow = 'VEÍCULO REGISTRADO',
            title = 'As chaves são suas',
            text = 'Pronto. Seu veículo foi registrado e já está aguardando na garagem.',
            paragraphs = {
                'Cuide bem dele. Uma cidade nova parece bem menor quando você tem como atravessá-la por conta própria.',
            },
            speaker = 'Edward',
            character = 'assets/characters/edward-guide.png',
            characterSide = 'left',
            choices = {
                { id = 'back', label = 'Voltar às opções', action = 'goto', target = 1, primary = true },
                { id = 'leave', label = 'Encerrar conversa', action = 'goto', target = 7 },
            },
        },
    },
}
